### ISSUE TITLE
OSX: examples not working on Rust nightly since 2018-03-15

### ISSUE THREAD

**Issue by eldyer** [tomaka/glutin#1005]
On OSX, all glutin examples panic with "Segmentation fault: 11" on Rust nightlies newer than nightly-2018-03-15.

Here the output of the window example:

> 'main' panicked at '~~~weak dyld: malformed executable '%s', skipping indirect symbol to %s
dyld: interp', /Users/eldyer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.11.2/src/platform/macos/window.rs:349:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::begin_panic
             at libstd/panicking.rs:402
   5: std::panicking::try::do_call
             at libstd/panicking.rs:349
   6: winit::platform::platform::window::Window2::new
             at /Users/eldyer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.11.2/src/platform/macos/window.rs:349
   7: winit::platform::platform::Window::new
             at /Users/eldyer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.11.2/src/platform/macos/mod.rs:32
   8: <&'a T as core::fmt::Debug>::fmt
             at /Users/eldyer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.11.2/src/window.rs:119
   9: glutin::platform::platform::Context::new
             at src/platform/macos/mod.rs:48
  10: alloc::slice::<impl [T]>::into_vec
             at src/lib.rs:313
  11: window::main
             at examples/window.rs:11
  12: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  13: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  14: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:102
  15: rust_panic
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  16: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  17: window::main
Segmentation fault: 11

**Comment by eldyer** [comment]
Seems to be related to:
https://github.com/tomaka/winit/issues/429
https://github.com/rust-lang/rust/issues/49275

**Comment by uberjay** [comment]
Looks like has been fixed in winit 0.11.3, but there hasn't been a glutin update to bump the dep yet. (it's still pointing at 0.11.2)

**Comment by parasyte** [comment]
@uberjay There is an open PR: https://github.com/tomaka/glutin/pull/1010

**Comment by uberjay** [comment]
Ah, excellent. Seems like I just stumbled into this a couple days early... otherwise I wouldn't have even noticed!

**Comment by parasyte** [comment]
Yeah, I've been following along in the shadows for a few days, myself. Yesterday I was working on updating `gfx` to use the pre-release branch from that PR: https://github.com/parasyte/gfx/tree/update/glutin-0.14
