### ISSUE TITLE
Cursor skipping

### ISSUE THREAD

**Issue by huntiep** [tomaka/glutin#1006]
I'm using glutin 13.1 on X11 Linux for a paint program. I've noticed that the cursor seems to skip several pixels even with normal movements. Here's an example:
![2018-03-26-235218_5200x1080_scrot](https://user-images.githubusercontent.com/28681177/37947568-73b656e0-3151-11e8-9c2b-6f2a4f11b056.png)

Is this a problem with glutin or a platform limitation that I need to work around?

**Comment by mitchmindtree** [comment]
This looks like pretty normal behaviour, assuming you're drawing a single dot per cursormoved event?

I'd imagine most paint/drawing programs work by interpolating between the received events or drawing lines between each point (rather than single dots).

**Comment by timvisee** [comment]
Yes, this is indeed normal. It might be slightly worse (or better) than other applications. Given that the application notifies of cursor updates 30 or 60 times a second, I can't imagine it being hard to move your mouse more than 60 pixels a second.

**Comment by huntiep** [comment]
I see, looking at mouse polling rates this makes sense. I'll just fill in the dots then. Thanks.
