### ISSUE TITLE
Update winit

### ISSUE THREAD

**Issue by Dooskington** [tomaka/glutin#1016]
Is there any reason why the dependency for winit hasn't been updated to 0.13 yet? I'm waiting on a fix for an issue which should be in the the newest version: https://github.com/tomaka/winit/issues/196

I just tried to build it myself with the updated dependency, but I guess the update broke a few things.
If there isn't anything in the works, I'd be happy to give it a shot and submit a PR.

**Comment by LPGhatguy** [comment]
See #1015.
