### ISSUE TITLE
Flickering issues with transparency

### ISSUE THREAD

**Issue by chrisduerr** [tomaka/glutin#1019]
I'm not sure if these issues have been reported to glutin yet, but they have been opened in alacritty a long time ago and just now when checking glutin's issues I wasn't able to find anything related to them.

These issues are not directly related to alacritty, but I have been able to reproduce them with the glutin examples too, it seems to be a general issue.

For a more elaborate discussion, please see the issues in the alacritty tracker:
https://github.com/jwilm/alacritty/issues/869
https://github.com/jwilm/alacritty/issues/969

### Issues
When glutin is started using `.with_transparency(true)` and the window is resized, it becomes completely transparent during the resize operation. Once the resize is done, the window will be back to the normal transparency.

This leads to a percieved "flickering" of the window and has been reported to cause issues with slow resizing (at least I'm pretty sure that's the cause for the bad resize perfromance reported by a few people).

To make the issue absolutely obvious here's a GIF:
https://u.teknik.io/awQS7.webm
This was recorded on an Archlinux/X11/i3/compton machine running the old ati video driver.

**Comment by francesca64** [comment]
Okay, here's something interesting. If you modify glutin to never use transparency, but keep it on in winit, then it still flickers. It just flickers to black instead of transparent.

**Comment by chrisduerr** [comment]
So this is an issue with winit, not glutin?

**Comment by francesca64** [comment]
It seems to be. If I remove all of winit's transparency code, transparency still works, and there's no flickering.

https://bugzilla.libsdl.org/show_bug.cgi?id=2101

Give this branch a shot: https://github.com/francesca64/winit/tree/x11-flicker

**Comment by chrisduerr** [comment]
@francesca64 That seems to do the job! Would be amazing to finally solve this issue.
