### ISSUE TITLE
CursorMoved and MouseInput events happening in title bar

### ISSUE THREAD

**Issue by Dooskington** [tomaka/glutin#1027]
On macOS High Sierra, it seems like I am getting window events that I shouldn't be, when clicking on the title bar / window decoration area.

Is this a bug or intentional? I think these window events should be restricted to happen only in the inner window. I even loaded up a C++ SDL project to check how they handle it, and it does ignore the equivalent events in the title bar.

**Comment by francesca64** [comment]
This should be reported to winit instead.

**Comment by Dooskington** [comment]
Okay, will do.
