### ISSUE TITLE
[RFC] Merging HeadlessContext and Context

### ISSUE THREAD

**Issue by keringar** [tomaka/glutin#1028]
I don't think there's currently any way to share a regular context with a headless context because of the split between HeadlessContext and Context. There's a couple differences between the two in their implementation, but API wise I don't think there's much use in separating them out (AFAIK). Any thoughts or are there better ways to create shared regular and headless contexts?

**Comment by ZeGentzy** [comment]
Would this change allow us to create a context without a window then share it with multiple windows? If so, Id be 100% aboard.

**Comment by keringar** [comment]
Yes I believe it should. The underlying contexts are interoperable, but right now we can't really pass one to the other because a headless context uses a platform:: HeadlessContext instead of a platform::ContextOn Jun 11, 2018 12:49 AM, Hal Gentz <notifications@github.com> wrote:Would this change allow us to create a context without a window then share it with multiple windows? If so, Id be 100% aboard.

**Comment by mitchmindtree** [comment]
Maybe rather than merging the two, we could have the shared context argument be a `&GlContext` (which both `Context` and `HeadlessContext` implement), though I don't remember if it should be as simple as swapping out some types or if this would require a more involved change.

**Comment by keringar** [comment]
I thought about that and we could use the ```GlContextExt``` trait to get the raw handle since the platform specific code needs access to the actual context handle. But even if we go that way than there's still a lot of code duplication between the ```Context``` and ```HeadlessContext``` that we could remove by merging the two. For example on windows, linux, and macos the headless context mostly just delegates to the inner ```Context``` .

**Comment by ZeGentzy** [comment]
Should be closed now.
