### ISSUE TITLE
Implement with_gl_debug_flag on cocoa

### ISSUE THREAD

**Issue by tomaka** [tomaka/glutin#105]

**Comment by fkaa** [comment]
OS X only implements OpenGL 4.1 and debug functionality is not available as an extension (https://developer.apple.com/opengl/capabilities/). We could possibly implement this functionality by providing our own implementation of the relevant functions, but it wouldn't be able to meet the requirements for the extension plus it's way out of scope for glutin.

Should the flag be ignored or panic if given? I prefer the former.

**Comment by tomaka** [comment]
There's no additional function when you create a debug context.
The only difference is that a debug context will check more things and generate more warnings/log messages.

**Comment by tomaka** [comment]
Let's just ignore it then.
