### ISSUE TITLE
Create window with physical dimensions

### ISSUE THREAD

**Issue by spearman** [tomaka/glutin#1052]
With the change to LogicalSize there's no way to create a window with desired physical dimensions without checking DPI and resizing after it's created.

**Comment by francesca64** [comment]
1. This is related to winit, not glutin. Feel free to re-report there.
2. This is discussed here: https://github.com/tomaka/winit/issues/591#issuecomment-403113701

**Comment by spearman** [comment]
My bad, didn't realize WindowBuilder was a winit re-export.
