### ISSUE TITLE
Glutin uses 200% mode for my screen when I've set 100% in the GNOME settings

### ISSUE THREAD

**Issue by pedrocr** [tomaka/glutin#1059]
I'm using Ubuntu 18.04 with the default GNOME/X session. My screen dimensions are as follows:

```
eDP-1 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 310mm x 174mm
```

glutin is detecting this as a HiDPI factor of 2 which is also the default in GNOME for this screen. I have however set the value to 1 in the GNOME settings so it would be good if glutin would follow that setting.

**Comment by francesca64** [comment]
1. This is an issue with winit, not glutin.
2. I believe this is related to tomaka/winit#606

**Comment by pedrocr** [comment]
I was going by the docs being in glutin:

https://docs.rs/glutin/0.18.0/glutin/dpi/index.html

And thanks for the reference, I'll start following that PR

**Comment by felixrabe** [comment]
That can be confusing indeed – I think the docs are often the same for glutin and winit because glutin re-exports winit functionality. You'll find the exact same section in the winit docs here:

https://docs.rs/winit/0.17.1/winit/dpi/index.html

**Comment by pedrocr** [comment]
Thanks for the explanation. Closing as the winit PR already has a fix even.
