### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by chrisduerr** [tomaka/glutin#1060]
So I've noticed for a while that Alacritty memory usage is a bit higher than I would like it to be. So I tried to investigate where the memory is coming from. I usually expected Alacritty do be the main factor here, however I've noticed that a big chunk of the memory usage is allocated during window initialization.

I can investigate this myself a bit when I've got the time, but I first wanted to open an issue and check if anyone else has ever looked into this. Is glutin already optimized for memory usage or are there some performance gains left to be made?

I've run the `window` example in winit, the `window` example in glutin and Alacritty itself. Initially I used gdb to step through Alacritty to check for memory usage, however running the standalone applications should make sure that it's not Alacritty's fault.

Memory usage comparison:

| Application | Memory Usage |
| ------------ | ---------------- |
| Winit           | 7M+                   |
| Glutin          | 55M+                 |
| Alacritty      | 65M+                 |

**EDIT:** This memory usage was recorded on a Linux system running X11/i3+compton.

**Comment by ZeGentzy** [comment]
Hey @chrisduerr sry for the late response.

So I took to investigating this issue, and I could successfully reproduce it. However, it's cause is not from us, but instead from mesa.

Here is a short C program which demonstrates that this is a mesa problem:
```
#include <GL/glx.h>

int main()
{
	Display* dpy = XOpenDisplay(0);
	const char* exts = glXQueryExtensionsString(dpy, DefaultScreen(dpy));
	while (true) {}
	XCloseDisplay(dpy);
}
```
The memory usage is caused by an internal call to `GetGLXPrivScreenConfig`. The majority of the memory usage can be attributed to this line on line 561 of `loader.c`, which on my computer successfully attempts to load `/usr/lib/dri/radeonsi_dri.so`:
```
         driver = dlopen(path, RTLD_NOW | RTLD_GLOBAL);
```
Here is a full backtrace.

```
#0  loader_open_driver (driver_name=driver_name@entry=0x100090e60 "radeonsi", out_driver_handle=out_driver_handle@entry=0x1000361b0,
    search_path_vars=search_path_vars@entry=0x7ffff73441d0 <search_path_vars>) at ../mesa/src/loader/loader.c:561
#1  0x00007ffff730fea2 in driOpenDriver (driverName=driverName@entry=0x100090e60 "radeonsi", out_driver_handle=out_driver_handle@entry=0x1000361b0)
    at ../mesa/src/glx/dri_common.c:108
#2  0x00007ffff7318365 in dri3_create_screen (screen=0, priv=0x1000328f0) at ../mesa/src/glx/dri3_glx.c:864
#3  0x00007ffff7304d39 in AllocAndFetchScreenConfigs (priv=0x1000328f0, dpy=0x100017910) at ../mesa/src/glx/glxext.c:823
#4  __glXInitialize (dpy=0x100017910) at ../mesa/src/glx/glxext.c:949
#5  __glXInitialize (dpy=dpy@entry=0x100017910) at ../mesa/src/glx/glxext.c:857
#6  0x00007ffff7300335 in GetGLXPrivScreenConfig (dpy=dpy@entry=0x100017910, scrn=scrn@entry=0, ppriv=ppriv@entry=0x7fffffffcc50, ppsc=ppsc@entry=0x7fffffffcc48)
    at ../mesa/src/glx/glxcmds.c:174
#7  0x00007ffff730089d in glXQueryExtensionsString (dpy=0x100017910, screen=0) at ../mesa/src/glx/glxcmds.c:1321
#8  0x00000001000011a6 in main () at mesa.cpp:9
```

I tested this against `mesa-git`. Here are the versions of what's installed on my pc:
```
pacman -Q | grep "mesa\|llvm\|clang\|glvnd\|vulkan\|amdgpu\|radeon\|libdrm\|amdvlk"
amdvlk-git r40.48d46fa-1
clang-svn 353932-1
clang-tools-extra-svn 353932-1
lib32-amdvlk-git r40.48d46fa-1
lib32-libdrm-git 6497.eba6609b-1
lib32-libglvnd 1.1.0-1
lib32-llvm-libs-svn 353942-1
lib32-llvm-svn 353942-1
lib32-mesa-git 107457.017349997fd-1
lib32-vulkan-icd-loader 1.1.99+3022+e1eafa18e-1
lib32-vulkan-radeon-git 107457.017349997fd-1
libdrm-git 6497.eba6609b-1
libdrm-git-debug 6497.eba6609b-1
libglvnd-git 1.1.0.r13.gf92208b-1
llvm-libs-svn 353932-1
llvm-ocaml-svn 353932-1
llvm-svn 353932-1
mesa-demos 8.4.0-1
mesa-git 107457.017349997fd-1
mesa-git-debug 107457.017349997fd-1
opencl-mesa-git 107457.017349997fd-1
vulkan-headers 1:1.1.99-1
vulkan-icd-loader 1.1.99+3022+e1eafa18e-1
vulkan-radeon-git 107457.017349997fd-1
vulkan-tools 1.1.96+6873+85ba793e-1
vulkan-validation-layers 1.1.96+8010+ebef1f33-1
xf86-video-amdgpu-git 485.5f91be7-1
xf86-video-amdgpu-git-debug 485.5f91be7-1
```

I'm afraid there is nothing we can do here. Please file a bug upstream @ the mesa devs.

cc @francesca64 Please close this issue.

**Comment by chrisduerr** [comment]
Looks like that's just the overhead  necessary to load the drivers for using OpenGL.

Thanks for looking into this @ZeGentzy!
