### ISSUE TITLE
ModifiersState not working

### ISSUE THREAD

**Issue by NyxCode** [tomaka/glutin#1062]
During a `MouseWheel` event, all fields of the `ModifiersState` struct are `false`, even when the according key is pressed.

`Linux 4.14.68-1`, `Gnome 3.28.3` on `Wayland`

**Comment by francesca64** [comment]
This is an issue in [winit](https://github.com/tomaka/winit), not glutin.

**Comment by NyxCode** [comment]
oups - you're right, didnt notice the modules were re-exported.
I will create an issue there, sorry.
