### ISSUE TITLE
Gnome wmclass is null in Wayland

### ISSUE THREAD

**Issue by sevagh** [tomaka/glutin#1067]
I created the following issue in alacritty: https://github.com/jwilm/alacritty/issues/1582

In Wayland, the running instance of Alacritty is not associated with the `.desktop` entry.

Is this something relevant to the glutin project?

**Comment by sevagh** [comment]
If I run the example, `cargo run --example window`, the example application is called "Unknown" in Gnome. 

When I run `WAYLAND_DISPLAY= cargo run --example window`, the example application is called "window".

**Comment by sevagh** [comment]
Seems like it comes from the file name. If I copy `window.rs` to `blahblah.rs`, it shows as `blahblah`. E.g.:

```
$ WAYLAND_DISPLAY= cargo run --example blahblah
```

![blahblah](https://user-images.githubusercontent.com/8574092/45920041-f753a680-be6c-11e8-9958-c8cacd596a15.png)

**Comment by sevagh** [comment]
Looks like it comes from winit: https://github.com/tomaka/winit/blob/b0e3865562da8cade5bcbb56f2e71e9d7eb41336/src/platform/linux/x11/window.rs#L237

```
let class = env::args()                                     
    .next()                                                 
    .as_ref()                                               
    // Default to the name of the binary (via argv[0])      
    .and_then(|path| Path::new(path).file_name())           
    .and_then(|bin_name| bin_name.to_str())                 
    .map(|bin_name| bin_name.to_owned())                    
    .or_else(|| Some(window_attrs.title.clone()))           
    .and_then(|string| CString::new(string.as_str()).ok())  
    .expect("Default `WM_CLASS` class contained null byte");```

**Comment by sevagh** [comment]
https://wiki.gnome.org/HowDoI/ChooseApplicationID#Things_that_use_application_IDs

**Comment by sevagh** [comment]
Somebody on the Gnome IRC pointed me to xdg-shell: https://github.com/wayland-project/wayland-protocols/blob/298d888ac718eae57ff2245d373d4327074506ea/stable/xdg-shell/xdg-shell.xml#L590

I noticed that the dependency in Winit on https://github.com/smithay/wayland-rs contains a reference to xdg-shell: https://github.com/Smithay/wayland-rs/blob/master/wayland-protocols/src/stable.rs#L23

At that point, I get a bit confused because I don't understand the code of `wayland-rs` so I don't think I'll be able to contribute more than this.

**Comment by francesca64** [comment]
This is relevant to winit rather than to glutin (and should've been reported to winit instead, though it's rather late for me to be mentioning that), and has been discussed a bit here: https://github.com/tomaka/winit/pull/497#issuecomment-387031205

**Comment by sevagh** [comment]
>This is relevant to winit rather than to glutin (and should've been reported to winit instead, though it's rather late for me to be mentioning that

It's definitely relevant to glutin because alacritty uses glutin and not winit.

**Comment by francesca64** [comment]
This functionality is (or would be) a component of winit, and glutin uses winit. I'm surprised @chrisduerr referred you here instead.

Regardless, @vberger is the person to ask about this.

**Comment by chrisduerr** [comment]
Yeah Alacritty uses winit through glutin. I just popped up the wrong link, winit is the better place for this.

Thanks for the quick reply @francesca64.
