### ISSUE TITLE
Window much slower to spawn with external monitor connected

### ISSUE THREAD

**Issue by jonhoo** [tomaka/glutin#1070]
I'm continuing down a rabbit hole that started in jwilm/alacritty#1603. Specifically, it looks like my terminal (`alacritty`), which uses `glutin`, is much slower to spawn its initial window in certain cases. In particular, on my laptop (a 6th generation Lenovo X1 Carbon, so new hardware), there is a marked difference in the time it takes to spawn a single `glutin` window depending on whether an external monitor is connected or not.

In particular, running the following code with `--release`:
```rust
extern crate glutin;
use glutin::GlContext;
fn main() {
    let events_loop = glutin::EventsLoop::new();
    let window = glutin::WindowBuilder::new().with_title("A fantastic window!");
    let context = glutin::ContextBuilder::new();
    let gl_window = glutin::GlWindow::new(window, context, &events_loop).unwrap();
    let _ = unsafe { gl_window.make_current() };
}
```
Without an external monitor connected:
```
0.04user 0.01system 0:00.19elapsed 32%CPU (0avgtext+0avgdata 16472maxresident)k
0inputs+8outputs (1major+1407minor)pagefaults 0swaps
```
With an external monitor connected:
```
0.03user 0.02system 0:00.52elapsed 12%CPU (0avgtext+0avgdata 16440maxresident)k
0inputs+8outputs (1major+1395minor)pagefaults 0swaps
```
That's 0.19s to 0.52s on the same system with a different monitor configuration, which seems surprising.

I took some perf profiles, though there's relatively little fidelity since I just spawn and immediately close a window. Without external monitor:
[![perf without external monitor](https://jon.thesquareplanet.com/share/glutin-noext.svg)](https://jon.thesquareplanet.com/share/glutin-noext.svg)
With external monitor:
[![perf with external monitor](https://jon.thesquareplanet.com/share/glutin-ext.svg)](https://jon.thesquareplanet.com/share/glutin-ext.svg)

The relevant lines from `xrandr -q` in the two configurations are:
```
Screen 0: minimum 320 x 200, current 2560 x 1440, maximum 8192 x 8192
eDP-1 connected 2560x1440+0+0 (normal left inverted right x axis y axis) 309mm x 174mm
   2560x1440     60.01*+  59.99    59.99    59.96    59.95
```
and
```
Screen 0: minimum 320 x 200, current 3120 x 1920, maximum 8192 x 8192
eDP-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 309mm x 174mm
   1920x1080     60.01    59.97    59.96*   59.93
HDMI-1 connected primary 1200x1920+1920+0 left (normal left inverted right x axis y axis) 546mm x 352mm
   1920x1200     59.95*+
   1920x1080     60.00    50.00    59.94    59.99
```

**Comment by francesca64** [comment]
Does this also happen with [winit](https://github.com/tomaka/winit), or it specifically with glutin?

**Comment by jonhoo** [comment]
@francesca64 I'd be happy to give it a shot, though don't have all that much working knowledge of `glutin` or `winit`. What's the equivalent `winit` program?

**Comment by francesca64** [comment]
I assume you were testing with `cargo run --example window` in glutin? The same command would work for winit.

**Comment by jonhoo** [comment]
Well, I was testing with the code in the first post, but it was adapted pretty straightforwardly from the included example. I'll give the `winit` example a shot once I get back to my external monitor (which sadly won't be for a few days due to Rust Belt Rust)

**Comment by jonhoo** [comment]
Yup, happens in `winit` directly too! Filed tomaka/winit#682.

**Comment by ZeGentzy** [comment]
Please try this PR by me: https://github.com/tomaka/winit/issues/682#issuecomment-466767319

**Comment by jonhoo** [comment]
I'll try to find some time to give this a shot tomorrow!

**Comment by ZeGentzy** [comment]
Closing as fixed upstream.
