### ISSUE TITLE
Window titles have an extra character at the end

### ISSUE THREAD

**Issue by vpzomtrrfrt** [tomaka/glutin#1083]
(see also jwilm/alacritty#1756)

Windows created by glutin appear to have an extra character at the end, which shows up as � since a recent i3wm update.  I've tested this with the "window" example and with Alacritty under Artix Linux with i3wm 4.16.

**Comment by vpzomtrrfrt** [comment]
I don't see this issue with the winit example I tested, just glutin.

I also tested on Openbox, where the character doesn't show up, but still exists (`xwininfo | xxd`).

**Comment by psychon** [comment]
Let's do some cross linking:
- Also reported to i3: https://github.com/i3/i3/issues/3515
- Already fixed in winit: https://github.com/tomaka/winit/pull/658

**Comment by Airblader** [comment]
This has been fixed here:

https://github.com/tomaka/winit/commit/b0e3865562da8cade5bcbb56f2e71e9d7eb41336#diff-b2a8e3c5b8b81b078b7c14f15d0c4f06

**Comment by francesca64** [comment]
Now that #1081 has been merged, this should be resolved.
