### ISSUE TITLE
Window size larger than declared

### ISSUE THREAD

**Issue by varomix** [tomaka/glutin#1087]
Hi,
I noticed the windows created with Glutin are far bigger than the specified size, anyone knows how to fix this issue? example >> 
You can  see the value on the code is smaller
thanks 

This is on Linux
![](https://i.imgur.com/zwK6A6t.png)

**Comment by varomix** [comment]
Hi
says hipdi factor: 1.5
weird cause I have a normal 1080 laptop

thanks

**Comment by varomix** [comment]
Actually this happened in both my 4K monitor and 1080 laptop

**Comment by ZeGentzy** [comment]
@varomix On X11, you can figure out the dimensions Xorg thinks your screen has using `xrandr | grep mm` We do some simple math using those numbers to decide the dpi, see https://github.com/tomaka/winit/blob/3c59283b3fbf409353413c0c0d7d39ae85287e60/src/platform/linux/x11/util/randr.rs#L7

The formula is `Max(((width_px * height_px) / (width_mm * height_mm) * (12.0 * 25.4 / 96.0)).round() / 12.0, 1)`. If you want, you can try computing it manually using the numbers `xrandr` provides. 

If `xrandr` provides the wrong dimensions for your monitor, you might consider manually correcting them as according to here: https://bbs.archlinux.org/viewtopic.php?id=239789

**Comment by ZeGentzy** [comment]
Closing. If this is still an issue, file it with winit.
