### ISSUE TITLE
Unnecessary API Restrictions on Context::new_shared

### ISSUE THREAD

**Issue by Osspial** [tomaka/glutin#1091]
Right now, we have a separation between `Context::new` and `Context::new_shared` for safety reasons. `Context::new_shared` can apparently cause safety issues, with the docs describing two scenarios in which unsafe behavior can occur (`shareable_with_windowed_contexts` and platform-specific API misuse). However, looking at the documentation there doesn't seem to be anything inherent to creating a context with shared lists that's unsafe.

* Unsafe behavior is allowed if `shareable_with_windowed_contexts` doesn't match between contexts, but there's no reason we can't keep track of that internally and safely throw an appropriate error.
* The errors described in `README-SHARING.md` aren't related to safety, and either cannot occur or can be handled with an `Err`:
  * The following errors cannot occur since we're managing context handles:
    * > glXCreateNewContext can generate the following errors: GLXBadContext if share list is neither zero nor a valid GLX rendering context; **(GLX)**
    * > • If is neither zero nor a valid context handle, then ERROR_INVALID_OPERATION is generated. **(WGL)**
  * None of the address space issues are valid since Rust processes only exist in a single address space.
    * > In a multi-threaded environment, all threads may share the same virtual address space; however, this capability is not required, and implementations may choose to restrict their address space to be per-thread even in an environment supporting multiple application threads. **(EGL)**
      * The Rust threading and `Send`/`Sync` API only make sense with a shared address space - it shouldn't be necessary to consider this in the context sharing API
  * Any creation errors reported by the OS are handled with `Err`.
  * Context incompatibilities (e.g. trying to share an `OpenGL` and `OpenGL ES` context) should be reported by the OS.

What's more, a *different* API lets you perform context sharing without the `unsafe` tag: `GlWindow::new`, which accepts a `ContextBuilder` with the `shared` attribute. If that's safe, why isn't `Context::new_shared`? `Context::new_shared` is a strictly more useful version of `Context::new` and doesn't justify its `unsafe` tag, so it may make sense to merge those APIs.

@ZeGentzy You seem to have written much of the documentation for context sharing. Is there anything I'm missing here that requires the function be unsafe?

**Comment by ZeGentzy** [comment]
>Unsafe behavior is allowed if shareable_with_windowed_contexts doesn't match between contexts, but there's no reason we can't keep track of that internally and safely throw an appropriate error

Additionally, we might also want to make sure that we don't share contexts of different versions.

>  None of the address space issues are valid since Rust processes only exist in a single address space.

I've been under the assumption this is an hardware thing? Is it not?

>  Any creation errors reported by the OS are handled with `Err`.
>  Context incompatibilities (e.g. trying to share an `OpenGL` and `OpenGL ES` context) should be reported by the OS.

I will note that sometimes they weren't, and instead I'd get a SEGV or memory corruption somewhere. Should we be responsible for funky drivers? Maybe. Could misusing `glutin` cause those issues? Tbh, probably not.

> @ZeGentzy You seem to have written much of the documentation for context sharing. Is there anything I'm missing here that requires the function be unsafe?

`README-SHARING.md` was more for me & the guy who asked for it then actual end users, it was a nice list of things not to fuck up when working with sharing. Most of the stuff is irrelevant to glutin's users tbh. 

Anyways, my rational for `unsafe` is that the specs are long and the rules are numerous and scattered. Even if we conform to all the rules, doesn't mean that the drivers do. Easy just to call it `unsafe` so that people know that if they use sharing that they should be careful.

**Comment by Osspial** [comment]
@ZeGentzy Thanks for the info!

> I've been under the assumption this is an hardware thing? Is it not?

I think it's technically possible for hardware to implement threads that way, but at that point it's essentially making a new process and is fundamentally incompatible with how the Rust threading API works. Take the following example:

```rust
use std::thread;

fn main() {
    // Creates a new heap-allocated string (which is implemented as a managed
    // pointer to a buffer).
    let s: String = "I'm a string allocated at runtime!".to_string();
    
    thread::spawn(move || {
        // If the new thread existed in a different address space, this operation
        // wouldn't work.
        println!("{}", s);
    });
    
    thread::sleep_ms(100);
}
```

If Rust threads had different address spaces from eachother in the same process, that code couldn't be declared safe. Since it's safe, Rust threads must share their address space.

> I will note that sometimes they weren't, and instead I'd get a SEGV or memory corruption somewhere. Should we be responsible for funky drivers? Maybe. Could misusing glutin cause those issues? Tbh, probably not.

What was being done that caused those issues? If it can't be caused by a user of the Glutin API (or can't be caught by us), we don't have to consider it in the API.

> README-SHARING.md was more for me & the guy who asked for it then actual end users, it was a nice list of things not to fuck up when working with sharing. Most of the stuff is irrelevant to glutin's users tbh.

If it's irrelevant to Glutin's end users, it probably shouldn't be included in the source tree/referenced in the documentation.

> Anyways, my rational for unsafe is that the specs are long and the rules are numerous and scattered. Even if we conform to all the rules, doesn't mean that the drivers do. Easy just to call it unsafe so that people know that if they use sharing that they should be careful.

It seems to me that the unsafety is caused by calling other OpenGL functions incorrectly, which is already unsafe. The actual process of creating a context with shared lists doesn't look like it can cause unsafe behavior with a proper wrapper, though.

**Comment by ZeGentzy** [comment]
Thanks @Osspial for explaining the threading stuff.

> What was being done that caused those issues? If it can't be caused by a user of the Glutin API (or can't be caught by us), we don't have to consider it in the API.

> It seems to me that the unsafety is caused by calling other OpenGL functions incorrectly, which is already unsafe. The actual process of creating a context with shared lists doesn't look like it can cause unsafe behavior with a proper wrapper, though.

I can't exactly recall what caused them, it was half a year ago. Anyways, after this conversation, I do think it would be a ok to remove the unsafe tag. Shall you submit the PR?

> If it's irrelevant to Glutin's end users, it probably shouldn't be included in the source tree/referenced in the documentation.

Agreed.
