### ISSUE TITLE
Context::new_context's shareable_with_windowed_contexts parameter only signficiant on Linux

### ISSUE THREAD

**Issue by Osspial** [tomaka/glutin#1095]
On non-Linux platforms, the parameter is either ignored or crashes the program if set to `true`. There doesn't seem to be a good reason for this to be a cross-platform parameter, much less one that invades the main API for creating headless contexts. Instead, it should be a parameter in a linux `ContextBuilderExt` trait that is named for what it actually does - choosing between a window-manager-backed context or an OSMesa context.

**Comment by ZeGentzy** [comment]
Hey @Osspial, this was a great idea which I'd never thought about. Should've cc'd me so that I'd done it earlier. :)
Been added to my growing PR, right here: https://github.com/tomaka/glutin/pull/1058

**Comment by ZeGentzy** [comment]
Fixed in #1101.
