### ISSUE TITLE
Allow getting monitor DPI scaling before creating a window

### ISSUE THREAD

**Issue by 5paceToast** [tomaka/glutin#1096]
It sometimes makes sense to define a window size in terms of a logical number, rather than raw pixels.
An example of this is a terminal emulator, that defines its window size as rows/columns.
In that example, the physical size (size of glyph * columns etc) is determined by the current monitor's DPI.
As such, please add the ability to query DPI information *before* a window is created.

The upstream issue on my mind is jwilm/alacritty#204, but I can see this applying to other use-cases (for example, tile-based games where you could define the window size based on how many tiles one wishes to see at a time, but that wish to scale their tiles based on DPI).

**Comment by ZeGentzy** [comment]
While this is a good idea, this is actually a winit issue.

**Comment by 5paceToast** [comment]
Okay. Given that winit is under the same namespace (`tomaka/`), would it be possible to move this bug there? (I know it can be done within organizations, not so sure about user namespaces)

**Comment by 5paceToast** [comment]
Moved to https://github.com/tomaka/winit/issues/785.
