### ISSUE TITLE
.hide_cursor(true) doing nothing

### ISSUE THREAD

**Issue by IgrauBezRuk** [tomaka/glutin#1098]
Hey! Trying to hide cursor on Windows 10 via hide_cursor(true) but it's still visible. For example grab_cursor(true) work properly. What can be a problem?
Thanks!

**Comment by IgrauBezRuk** [comment]
Just noticed. Only in debug it visible.

**Comment by ZeGentzy** [comment]
Hey @IgrauBezRuk sry for the late response

Could you please post a small example of the code you got, and what you expect it to do, so that I can take a look at your problem?
