### ISSUE TITLE
Update to winit 0.19 and publish glutin 0.20

### ISSUE THREAD

**Issue by paulrouget** [tomaka/glutin#1114]
Is it possible to publish a new version based on the newly released winit?

**Comment by Osspial** [comment]
cc @ZeGentzy. I believe the way it's set up is that pushing a version to master with a new version number in `Cargo.toml` will automatically upload to crates.io, so it should be fairly simple to do.

**Comment by ZeGentzy** [comment]
#1110

**Comment by ZeGentzy** [comment]
@Osspial Doesn't seam to have worked. cc @tomaka

**Comment by ZeGentzy** [comment]
I've managed to publish all the new subcrates with `for cr in `for cr in glutin*; do echo "$cr"; done | sort -r | grep -v "_examples"`; do echo "Doing $cr"; cd "$cr"; cargo publish; cd ..; done`, but once it gets to `glutin`, it tells me I ain't the owner.

**Comment by Osspial** [comment]
It looks like since glutin proper is no longer in the crate root, the travis script isn't working anymore. This is the error in [the latest build](https://travis-ci.org/tomaka/glutin/jobs/504163749):

```
0.03s$ [ $TRAVIS_BRANCH = master ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    cargo publish --token ${CRATESIO_TOKEN}
    
error: manifest path `/home/travis/build/tomaka/glutin/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace
```

**Comment by ZeGentzy** [comment]
Ah, okay. #1117 has fixed this. @tomaka Can you please accept the ownership invites I sent @ crates.io.
The `glutin_*_sys` packages won't update in the future until you do.
