### ISSUE TITLE
Impossible to exit fullscreen mode on x11

### ISSUE THREAD

**Issue by tomaka** [tomaka/glutin#148]
The fullscreen example will cover the whole screen.
Alt+tab doesn't work, Ctrl+c doesn't work, Esc doesn't work. There's no way to exit fullscreen mode.

Apparently this is due to events not being received.

(I recommend testing on a virtual machine, unless you want to lock up your system)

**Comment by rsaarelm** [comment]
I was just testing fullscreen mode on i3wm, ran into this. The input events aren't going to the fullscreen app, but they do seem to keep going to the terminal where I started the app from instead. So Ctrl-C to exit did work for me since it stopped the program being run in the terminal.

**Comment by tomaka** [comment]
Closing in favor of #509
