### ISSUE TITLE
X11 only creates 3.0 contexts

### ISSUE THREAD

**Issue by tomaka** [tomaka/glutin#16]
See #2

**Comment by tomaka** [comment]
cc @kvark (I wanted to link this issue where you pinged me, but closed the tab and don't remember where it was).

The reason is simple: when you pass `Latest`, glutin doesn't specify any GL version when creating the context, so they default to `1.0 or something compatible`.

If the driver supports compatibility profiles, you'll likely get a 4.5 compatibility context, but if the driver doesn't support them you'll likely get a 3.0 context.

**Comment by kvark** [comment]
Huh, I'm pretty sure my driver supports the compatibility profile and LG up to 3.3
