### ISSUE TITLE
Change the way you get a window

### ISSUE THREAD

**Issue by tomaka** [tomaka/glutin#175]
On some platforms like Android, iOS, emscripten, etc. you only ever get one "window", and it is already created when you start.

Therefore the API should be more like `glutin::get_window()` instead of `glutin::Window::new`.

**Comment by aepsil0n** [comment]
Is this API still compatible with multi-window applications on desktop platforms?

**Comment by tomaka** [comment]
I don't really know how the API would look like yet.
I opened this issue mostly because it's not correct to "create" a window on android, since you already have one.

If you or someone happens to have a suggestion, that would be welcome.

**Comment by aepsil0n** [comment]
Well, I would say that such a fundamental difference in platform behaviour should be reflected in the API. So getting the single Android window should be something different than creating a window on a regular desktop. In my opinion either should fail on the wrong platform. On top of that we could provide a platform-agnostic wrapper function that gets the single window on Android, while it creates some default window on another platform. Let's just make sure that we do not impose any limitations of mobile apps on desktop apps.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/33

**Comment by seivan** [comment]
@tomaka You can have multiple windows (if you're referring to `UIWindow`) and it's not a bad idea to be able to create one if you want to switch between multiple Windows. One scenario could be toggling between Game and Menu states where Menu is using native UIKit/Swift and Game is written in Rust.

**Comment by francesca64** [comment]
@seivan your comment would have better visibility on the relevant winit issue (tomaka/winit#33).

**Comment by seivan** [comment]
@francesca64 Thanks!
