### ISSUE TITLE
Suggestion: Convert Keyboard Input Events to Characters (UTF8,...)

### ISSUE THREAD

**Issue by sbward** [tomaka/glutin#201]
I think there should be a way to easily get the actual character associated with a keyboard key press.  If I'm not mistaken, this would currently have to be implemented by the user, with something like a character mapping to a subset of `VirtualKeyCode` variants.

**Comment by jdm** [comment]
Related: #249

**Comment by aepsil0n** [comment]
I'm confused… isn't this what `glutin::Event::ReceivedCharacter(char)` is for?

**Comment by jdm** [comment]
Ah, yes. It doesn't have any association with the state of the key however, so it's really difficult to use for things like DOM key events that should have a displayable character regardless of pressed/released status.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/34
