### ISSUE TITLE
Provide infinite event iterator

### ISSUE THREAD

**Issue by aepsil0n** [tomaka/glutin#212]
To model the notion of a game loop as an object rather than a control structure is quite desirable for compositionality. The current event iterators in glutin, `poll_events` and `wait_events` do not really provide that notion, as they are quickly exhausted.

**Comment by tomaka** [comment]
That's what https://github.com/tomaka/glutin/pull/70 was supposed to do

**Comment by aepsil0n** [comment]
Oh, I missed that. Should have searched the issue list for *iterator* instead of *event*.

**Comment by tomaka** [comment]
Let's close it when it's done!

**Comment by aepsil0n** [comment]
Ah, okay, I thought this was effectively a duplicate of #28.

**Comment by tomaka** [comment]
Oh, you're right, it's a duplicate.
