### ISSUE TITLE
glXChooseFBConfig returns null for X11 target

### ISSUE THREAD

**Issue by ghost** [tomaka/glutin#24]
Hi,

I'm using Linux (Fedora) on a virtual machine, so that might be why I get this error (checked on dual boot with another machine and it worked fine).
It seems that the errors are due to the settings of GLX_X_RENDERABLE and GLX_X_VISUAL_TYPE.
If I set them both to GLX_DONT_CARE (default values), I can run the test and open the window (i.e. ./target/test/window).
Obviously this solution is not optimal, as GLX_X_RENDERABLE should be set to true, so I didn't create a pull request for that.

**Comment by ZeGentzy** [comment]
Is this still an issue? Please reopen if it is.
