### ISSUE TITLE
Layout of `ffi::XErrorEvent` does not match Xlib.h

### ISSUE THREAD

**Issue by akiss77** [tomaka/glutin#244]
On the two Ubuntu-based machines I have access to, the package libx11-dev has the following version information:
```
libx11-dev:arm64       2:1.6.2-1ubuntu2
libx11-dev:amd64       2:1.6.2-1ubuntu2
```

On both systems, Xlib.h contains the following declaration for `XErrorEvent`:

```
typedef struct {
        int type;
        Display *display;       /* Display the event was read from */
        XID resourceid;         /* resource id */
        unsigned long serial;   /* serial number of failed request */
        unsigned char error_code;       /* error code of failed request */
        unsigned char request_code;     /* Major op-code of failed request */
        unsigned char minor_code;       /* Minor op-code of failed request */
} XErrorEvent;
```

Here, the `resourceid` field is in the middle of the struct, while `XErrorEvent` in x11/ffi.rs has it as the last field. This causes that error reporting in an application becomes meaningless (the actual problem I'm having right now is in Servo).

First I though to submit a PR to reorder the fields but then found some pages by googling which document `XErrorEvent` the way it is implemented here. So now I'm not sure whether a reordering of fields would cause trouble for someone else out there, and if so, how to detect the layout on a given system?

(Still, I'm happy to submit a PR if you think that's the way to go.)

**Comment by tomaka** [comment]
cc @glennw

**Comment by glennw** [comment]
@akiss77 I just checked the Xlib.h on my system and it matches what you have found. I suspect the reference docs I was reading were incorrect / out of date. Since all three systems we've checked have the struct layout as you've described above, I'd suggest opening a PR with the changes to reorder the fields. Thanks!

**Comment by tomaka** [comment]
@glennw Thanks for investigating this! I was away for the week end
