### ISSUE TITLE
Mouse movements leading to crash with cocoa

### ISSUE THREAD

**Issue by tomaka** [tomaka/glutin#248]
From https://github.com/tomaka/glium/issues/425#issuecomment-72496265:

> Running the window example from Glutin has the same error, keyboard and clicks work fine, while mouse movement crashes with this crash report: http://pastebin.com/VjV4gWzd

**Comment by adudney** [comment]
All examples have the same error for me, except for multi window, as that dispatches 3 separate threads (Which crashes even before I move the mouse)

**Comment by adudney** [comment]
Multi window crash report: http://pastebin.com/a2bDTwhP

**Comment by simnalamburt** [comment]
![](http://i.imgur.com/5t5dJJp.png)

**Comment by tomaka** [comment]
Oh that's probably useful!

cc @bjz

**Comment by simnalamburt** [comment]
My smallest error reproduction:

```rust
extern crate glutin;

fn main() {
    let mut window = glutin::Window::new().unwrap();
    window.wait_events().next();
    window.wait_events().next();
}
```

**Comment by bjz** [comment]
Thanks! I'll have to fix the rust-cocoa bindings. For now we can call `msgSend_stret` directly. It'll be a few hours before I get home, but if you submit a PR that does something like: `msgSend_stret()(..., selector("locationInWindow"))` I can hit merge for you.

**Comment by bjz** [comment]
Ugh, seems I [caused a regression](https://github.com/servo/rust-cocoa/commit/78509d02d8cc29bc33ab9d06ca54a6c24ea3c532#diff-8550f09508786ee2e01c09c7d4722142R1848) in servo/rust-cocoa#59. It's really hard to know what needs `msgSend` or `msgSend_stret`...

**Comment by bjz** [comment]
And thanks for the awesome sleuthing @simnalamburt!

**Comment by bjz** [comment]
What are you using for the stack trace? Instruments?

**Comment by simnalamburt** [comment]
Wow! @bjz, thanks for your fix.

Actually that was just Xcode debugger (graphical lldb frontend). I'm pretty new with OS X, even don't know what `msgSend_stret` is, I just choosed Xcode just because it was already installed in my MBA and it looks easier than CLI lldb. Instruments.app looks awesome by the way! (Real time resource inspector, OpenGL inspector, etc)

**Comment by bjz** [comment]
It would be great if you could do a tutorial on it - I prefer a graphical debugger to the command line.
