### ISSUE TITLE
Include the displayable characters with key events

### ISSUE THREAD

**Issue by jdm** [tomaka/glutin#249]
For example, on OSX we could use https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSEvent_Class/#//apple_ref/occ/instm/NSEvent/charactersIgnoringModifiers (or maybe the characters selector; I'm not certain which is more appropriate).

**Comment by jwatt** [comment]
Note also that the current use of NSEvent::keyCode in src/cocoa/mod.rs appears to be wrong since cocoa and glutin's definitions of 'virtual key' seem to be different:

http://stackoverflow.com/questions/18408565/map-nsevent-keycode-to-virtual-key-code

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/34
