### ISSUE TITLE
Glutin is eating numbers and other special characters on linux

### ISSUE THREAD

**Issue by Manishearth** [tomaka/glutin#251]
https://github.com/servo/servo/issues/4839

Servo isn't being notified of key events for characters other than [A-Za-z]. I think Enter, space, arrow keys, and backspace work, but not much else.

This seems to be an issue with glutin (since we don't do platform-specific stuff when it comes to handling keys)

**Comment by tomaka** [comment]
Oh, it's most likely because a lot of stuff here is not implemented: https://github.com/tomaka/glutin/blob/master/src/x11/window/events.rs

**Comment by Manishearth** [comment]
Do we just have to uncomment the relevant lines?

**Comment by glennw** [comment]
Yes, that should be all that's needed.

**Comment by tomaka** [comment]
@Manishearth The most difficult part is to find the relevant entry in `Event::VirtualKey`.

Note that the elements in `Event::VirtualKey` were copy-pasted from Microsoft's documentation and then slightly adapted. So if they don't have an explicit name don't hesitate to change them as well (as long as you make sure not to break win32/osx/android).

**Comment by TyOverby** [comment]
What is keeping all of those lines from being uncommented?

On Wed, Feb 4, 2015 at 3:16 PM, tomaka <notifications@github.com> wrote:

> @Manishearth <https://github.com/Manishearth> The most difficult part is
> to find the relevant entry in Event::VirtualKey.
>
> Note that the elements in Event::VirtualKey were copy-pasted from
> Microsoft's documentation and then slightly adapted. So if they don't have
> an explicit name don't hesitate to change them as well (as long as you make
> sure not to break win32/osx/android).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomaka/glutin/issues/251#issuecomment-72961333>.
>



-- 
-Ty Overby
:wq

**Comment by Manishearth** [comment]
I couldn't find any virtual keys for them and I'm hesitant to add more without understanding it better and having a way of testing it.
