### ISSUE TITLE
Testing Glutin with Gfx/OpenGL/Glium

### ISSUE THREAD

**Issue by bvssvni** [tomaka/glutin#265]
@aepsil0n got glium_graphics working, and I've worked on glutin_window for Piston since yesterday.

I have a game which compiles with GLFW/Glutin/SDL2 by changing a setting in Cargo.toml

https://github.com/bvssvni/rust-snake

The game renders a ridiculous high amount of circles, so it fits nicely as a testbed for different graphics back-ends. The plan is to add glium_graphics and see how it performs compared to the Gfx and OpenGL back-ends.

There is a problem (running on OSX:

- When pressing a key, it beeps!

**Comment by bvssvni** [comment]
glium_graphics is not added yet, so the bugs should be in glutin_window or glutin.

**Comment by bvssvni** [comment]
```
rustc 1.0.0-nightly (00df3251f 2015-02-08 23:24:33 +0000)
```

**Comment by bvssvni** [comment]
You can turn on/off updating the title by comment/uncomment https://github.com/bvssvni/rust-snake/blob/master/src/snakeapp.rs#L113

**Comment by bvssvni** [comment]
Updating title is now fixed, and it doesn't hang (due to bug in glutin_window). I updated comments, removing outdated information.

**Comment by fkaa** [comment]
The beep pressing got fixed in 44e954895fd6c3497c8b5483e1b3efe160429329.

**Comment by bvssvni** [comment]
Confirmed! Thanks!
