### ISSUE TITLE
Emscripten support roadmap

### ISSUE THREAD

**Issue by tomaka** [tomaka/glutin#27]
Related: https://github.com/rust-lang/rust/issues/2235

Work is being done on the [emscripten branch](https://github.com/tomaka/gl-init-rs/tree/emscripten)
- [ ] Basic support
- [ ] Inputs

**Comment by iceiix** [comment]
> Work is being done on the [emscripten branch](
https://github.com/tomaka/gl-init-rs/tree/emscripten)

This link is broken, is this the latest status? https://github.com/tomaka/glutin/issues/856 Platform support for emscripten (also this open pull request but it has conflicts: https://github.com/tomaka/glutin/pull/857 Improve Emscripten support)

**Comment by francesca64** [comment]
@iceiix this issue is very outdated. A better place to ask about Emscripten support is over on [winit](https://github.com/tomaka/winit); feel free to open an issue there.

**Comment by iceiix** [comment]
https://github.com/tomaka/winit/issues/760
