### ISSUE TITLE
Modify events iterators behavior

### ISSUE THREAD

**Issue by tomaka** [tomaka/glutin#28]
`wait_events` and `poll_events` should return *permanent* iterators, ie. iterators that can be reused later.
`wait_events` should not block but instead return an iterator that blocks when `next` is called.

**Comment by aepsil0n** [comment]
Would it be okay to provide this in the high-level API before #70 is complete? Since `wait_events` blocks atm, it would be quite easy to make an iterator with the desired behaviour that gets a new `WaitEventsIterator`, as soon as the old one is exhausted.

**Comment by tomaka** [comment]
That's a good idea!
