### ISSUE TITLE
Strange behaviour on OSX with Retina display.

### ISSUE THREAD

**Issue by mitchmindtree** [tomaka/glutin#287]
Here is what the conrod example looks like on my regular monitor.

![screen shot 2015-02-22 at 5 53 00 am](https://cloud.githubusercontent.com/assets/4587373/6315506/5b2156f2-ba58-11e4-9cfa-f4f5c32422ed.png)

And here is what it looks like after I drag the window across to my retina laptop display.

![screen shot 2015-02-22 at 5 53 17 am](https://cloud.githubusercontent.com/assets/4587373/6315509/6bc844ac-ba58-11e4-9d15-2e117f0e08d3.png)

Resizing seems to cause the background of the whole window to redraw as the correct background colour (however with the rest of the content still at half dimensions). Resizing the window inward also seems to shift the content halfway down the window vertically, while chopping the content horizontally at half the width of the window. The following shot is after resizing the window inwards slightly.

![screen shot 2015-02-22 at 6 06 06 am](https://cloud.githubusercontent.com/assets/4587373/6315528/2e6c7442-ba59-11e4-8fc0-5ae5e0c55323.png)

OSX 10.10.2

**Comment by bvssvni** [comment]
This has probably something to do with a wrong setup of absolute transform matrix in Piston.

**Comment by bvssvni** [comment]
We're still investigating this, but it seems to be something wrong when using the Glutin back-end, because the SDL2 back-ends works. I haven't found any bugs in glutin_window so far.

**Comment by TyOverby** [comment]
Are you correctly using the [hidpi_factor](http://tomaka.github.io/glutin/glutin/struct.Window.html#method.hidpi_factor) in your transformations?

**Comment by mitchmindtree** [comment]
@TyOverby have you managed to use the hidpi_factor successfully on a retina display? The PistonDevelopers/glutin_window is using it [like this](https://github.com/PistonDevelopers/glutin_window/blob/master/src/lib.rs#L129) and although the dimensions are better, the window still only displays clipped in the bottom left quarter [like this](https://github.com/PistonDevelopers/conrod/issues/363#issuecomment-92007706). Do you have any ideas on what could be missing? Any suggestions would be super appreciated if you get a chance :)

**Comment by tomaka** [comment]
`draw_size` right below doesn't seem to use it.

**Comment by mitchmindtree** [comment]
@tomaka Good call! I had tried this before with no luck, but tried again after you mentioned it - turns out it needed to be removed from the `size`, added to the `draw_size` and also added to cursor position - seems to work fine now. Cheers.

Going to close this now, but if anyone's still running into this, feel free to reopen.

Fixed in glutin_window by [this PR](https://github.com/PistonDevelopers/glutin_window/pull/29).
