### ISSUE TITLE
Error: can't find crate for `gl`

### ISSUE THREAD

**Issue by mikefarah** [tomaka/glutin#292]
Following the example in the readme, I added
```
glutin = "*"
```
as a dependency, then copy pasted the code under 'usage' and got 
```
Error: can't find crate for `gl`
```
when running cargo build :(

**Comment by mikefarah** [comment]
Also tried
```
[dependencies.glutin]
git = "https://github.com/tomaka/glutin"
```

Oh and I'm running Window$ 7

**Comment by mikefarah** [comment]
Sorry, I also forgot to mention that cloning and running the examples work..

**Comment by tomaka** [comment]
You need to add a dependency for `gl` if you want to try the example.

I've opened a PR to make it explicit in the README.
