### ISSUE TITLE
build_glium() not implemented

### ISSUE THREAD

**Issue by ragingSloth** [tomaka/glutin#309]
I'm trying to build the first glium example, and rustc is failing with 

`error: type glutin::window::WindowBuilder<'_> does not implement any method in scope named build_glium`

my code includes `use glium::DisplayBuild;`, so I believe the function should be defined

**Comment by tomaka** [comment]
Glium was recently changed to use the crates.io version of glutin.
If your code uses the git repository, then Rust considers that the git version of glutin and the crates.io version of glutin are two different libraries.

**Comment by tomaka** [comment]
I'll close this issue. Please re-open an issue in [the glium repo](https://github.com/tomaka/glium) if you still have a problem!
