### ISSUE TITLE
Publish an update to glutin_core_foundation for beta rust

### ISSUE THREAD

**Issue by SSheldon** [tomaka/glutin#353]
Another crate update request :smile:

glutin_core_foundation, a dependency of glutin_core_graphics, was updated for stable rust with servo/rust-core-foundation#60, so an update will need to be published for it to work on the beta. Thanks!

**Comment by tomaka** [comment]
Done

**Comment by SSheldon** [comment]
Thanks! All the OSX specific dependencies should be beta-ready now!
