### ISSUE TITLE
Apparently there's still problems with closing windows on OS X

### ISSUE THREAD

**Issue by bobakker** [tomaka/glutin#358]
The good news is that the window DOES close now. The bad news is that the program just keeps running. No resources are deallocated, and the program doesn't quit unless you ctrl-c it. I suspect this is because the window_should_close doesn't tell glutin to stop running, but I have no idea how to fix this. Any ideas?

**Comment by bobakker** [comment]
I think I figured it out. Although the window closes, no ```Closed``` event is ever triggered. I don't see one in ```PollEventsIterator```. I have no idea what event Cocoa triggers if a window is closed, or if it triggers one at all. It's also possible that it gets stuck somewhere in one of the wrappers. 

It wouldn't be too hard to fix this without using events at all, but it'd be a pretty ugly fix. I mean, you could simply put something like this in ```PollEventsIterator.next()```:

``` rust
if(self.window.delegate.state.is_closed) return Some(Closed);
```

But if possible, I'd like to fix it the proper way.

**Comment by tomaka** [comment]
This just needs to add `window.pending_events.push(Closed);` (here)[https://github.com/tomaka/glutin/blob/70d36a3d3d6afba3e89faf4d3979118f9c076fe9/src/cocoa/mod.rs#L72-L77].

However I don't know how that delegating stuff works, and I don't have a mac to test it.

**Comment by bobakker** [comment]
Works like a charm. I'll submit a PR.
