### ISSUE TITLE
Fullscreen seems to be broken on Windows

### ISSUE THREAD

**Issue by nstoddard** [tomaka/glutin#374]
I'm trying to run glium's `fullscreen` example, and when i press enter to switch to fullscreen I get this error:

```
Press Enter to switch fullscreen mode
thread '<main>' panicked at 'Failed to find the primary monitor', C:\Users\Nathan\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.0.23\src\win32\monitor.rs:143
An unknown error occurred
```

I'm on Windows 7, 64-bit.

**Comment by rsaarelm** [comment]
I'm getting this too. I'm not even trying to switch to full screen, just using get_primary_monitor() to get the current resolution. Also Win7, 64-bit.
