### ISSUE TITLE
Error when switching to fullscreen on Windows

### ISSUE THREAD

**Issue by nstoddard** [tomaka/glutin#379]
When I run glium's fullscreen example and try to switch to fullscreen, this happens:

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: GlutinCreationError(OsError("OpenGL context creation failed: The operation completed successfully.\r\n (os error 0)"))', C:/bot/slave/nightly-dist-rustc-win-64/build/src/libcore\result.rs:774
```

This happens both with my NVIDIA card and with integrated graphics.

**Comment by tomaka** [comment]
Is it only with the fullscreen example?

**Comment by nstoddard** [comment]
It doesn't happen in windowed mode or any of the other examples I've tried. Are there any other examples I should test?

**Comment by tomaka** [comment]
This may be due to this line: https://github.com/tomaka/glutin/blob/226c1b96fdd0f03bfec4fed4e2cc36bc769c23e2/src/win32/init.rs#L316

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/37
