### ISSUE TITLE
Replace Xlib by XCB written in Rust

### ISSUE THREAD

**Issue by tomaka** [tomaka/glutin#386]
## Motivation

- Linking to xlib at compile-time forces people to have xlib installed. This is not problematic for the moment, but it will be once wayland is supported.
- Xlib has a lot of race conditions. PRs like #221 are hacky. XCB can be implemented in safe Rust, which would mean less crashes.

## Process

- Rewrite XCB in Rust, by generating code from the XML files.
- Use xcb-rs for window creation and events handling.
- Use xlib/glx for OpenGL context creation by `dlopen`ing the appropriate libraries. See http://xcb.freedesktop.org/opengl/. Unfortunately video drivers are tightly coupled to Xlib, so it's not possible to entirely remove it.

## Alternatives

Wait for Wayland to be the most used windowing system, which should be the case around 2084.

**Comment by glennw** [comment]
This is a fantastic idea - just today I have run into two xlib related threading issues in servo.

**Comment by tomaka** [comment]
Unfortunately I don't think it's possible, except if we replicate the internals of libxcb.

**Comment by cmr** [comment]
@tomaka is there are particular problem with replicating its internals? I just took a look around and it doesn't seem too bad. (I think I might volunteer to implement this...)

**Comment by tomaka** [comment]
I'm not sure if that's a good idea, though.

You have to use xlib to open an X connection (that will be passed to GLX), then get a pointer to the XCB object from the `Display`.

You would therefore lose most of the advantages that using Rust would bring. It wouldn't bring anything over using XCB directly.

**Comment by rtbo** [comment]
@tomaka FYI I reactivated rust-xcb development this year. handling `Display `and `xcb::Connection` is feasible in a _relative_ clean way. I made an example to show how to setup an open gl display (`xlib_xcb` feature adds a `Display` pointer in the `Connection` object)

**Comment by Ben-Alderson** [comment]
I'd love to see glutin get support for xcb as well. The vulkan implementation on my computer only has support for VK_KHR_xcb_surface and not VK_KHR_xlib_surface.

**Comment by kvark** [comment]
@Ben-Alderson see https://github.com/tomaka/winit/issues/5
