### ISSUE TITLE
Cocoa support roadmap

### ISSUE THREAD

**Issue by tomaka** [tomaka/glutin#4]
- [x] Basic support
 - [ ] Input events
 - [ ] Hints
 - [ ] GL versions
 - [ ] Monitors
 - [x] Fullscreen

**Comment by SSheldon** [comment]
@tomaka, cocoa support's been around for a while, is there anything from this issue that wasn't completed or can it be closed?

**Comment by tomaka** [comment]
Yeah, I'll close all these roadmaps in favor of individual issues.
