### ISSUE TITLE
Make window centered

### ISSUE THREAD

**Issue by Kagami** [tomaka/glutin#438]
Would be nice to have ability to center window created by glutin. By default or with additional function call. Or at least to have ability to specify window's (x, y) position.

Seems like in OS X implementation windows are centered by default: https://github.com/tomaka/glutin/blob/119bd6393f5f3b8e1510ba6ab3281c8fb387449f/src/api/cocoa/mod.rs#L451

**Comment by Kagami** [comment]
Oh, there is actually `set_position` function. Don't know how I was able to miss it.
So it's in fact possible to center the window with glutin, you just need to calculate the coords by yourself.

**Comment by fkaa** [comment]
The documentation for `NSWindow::center` states:

> The window is placed exactly in the center horizontally and somewhat above center vertically. Such a placement carries a certain visual immediacy and importance. [...]

> You typically use this method to place a window—most likely an alert dialog—where the user can’t miss it. [...]

We should probably manually calculate the position to make it exact.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/38
