### ISSUE TITLE
is_closed doesn't work on X11

### ISSUE THREAD

**Issue by Kagami** [tomaka/glutin#442]
Hi.

I think `window.is_closed` helper doesn't correctly work with Linux & X11: I compiled example from readme (https://github.com/tomaka/glutin#usage) and can't close glutin window as usual. I can correctly catch and process `Event::Closed` event with `poll_events()` though.

I'm using XMonad WM if that matters.

**Comment by schulzch** [comment]
Same issue for Win32. Smells like a missing test case.

**Comment by tomaka** [comment]
I can't test case this. It would require a user to manually close the window.

**Comment by schulzch** [comment]
How about:

```rust
let window = glutin::Window::new().unwrap();
assert!(!window.is_closed());
window.hide(); // Not sure if it actually closes the window. If not provide a window.close().
assert!(window.is_closed());
```

Anyways... you really do not want to re-code helpers for every platform. I think `is_closed()` should be generalized, as its a helper after all.

**Comment by tomaka** [comment]
`is_closed` is supposed to call `PlatformSpecificGetWindowStatus` if it exists.
I think that the current os/x and X11 implementations have just been copied-pasted from win32, and the win32 implementation is badly written.

**Comment by schulzch** [comment]
I think using `PlatformSpecificGetWindowStatus` and friends is a bad idea. It'll complicate platform specific code and make your library users cry: no one would expect to have a platform specific performance penalty from `is_closed`. It'll be worse if you have to call the function from a specific thread on some platforms. When using `is_closed` I'd expect something like this internally:

```rust
let mut done = false;
while !done {
    for event in window.poll_events() {
        match event {
            glutin::Event::Closed => done = true,
            _ => {}
        }
    }
}
```

Another flawed thing about polling interfaces is: they drain battery life. I know GLUT and SDL have promoted them for over a decade, but most mobile games do something like this to safe battery life:

```C++
Uint32 animationTick(Uint32 interval, void*)
{
    // Prevent flooding event queue by testing if event is already pushed.
    SDL_Event event;
    if (SDL_PeepEvents(&event, 1, SDL_PEEKEVENT, SDL_USEREVENT,
            SDL_USEREVENT) == 0) {
        memset(&event, 0, sizeof(SDL_Event));
        event.type = SDL_USEREVENT;
        SDL_PushEvent(&event);
    }

    return interval;
}

int main(int argc, char** argv)
{
	//XXX: initialize SDL, Window and OpenGL...

	// Initialize animation timer.
    SDL_TimerID Timer = SDL_AddTimer(15, &animationTick, nullptr);
    if (!Timer) {
        SDL_LogMessage(SDL_LOG_CATEGORY_VIDEO, SDL_LOG_PRIORITY_CRITICAL,
            "Could not initialize animation Timer: %s\n",
            SDL_GetError());
        return -1;
    }
	
	// Event loop.
    bool done = false;
    while (!done) {
        SDL_Event event;
        if (!SDL_WaitEvent(&event)) {
            SDL_LogMessage(SDL_LOG_CATEGORY_ERROR, SDL_LOG_PRIORITY_CRITICAL,
                "Waiting for events failed: %s\n", SDL_GetError());
            return -1;
        }
		if (event.type == SDL_QUIT) {
			done = true;
		} else if (event->type == SDL_USEREVENT) {
			//XXX: render
			SDL_GL_SwapWindow(Window);
		} else {
            //XXX: process event in some sub-system.
        }
    }
}
```

**Comment by tomaka** [comment]
> When using is_closed I'd expect something like this internally:

Which means that if the user catches the `Closed` event then calls `is_closed()`, it would return `false`.

The function is named `is_closed` and not `handle_the_game_loop`. It is only supposed to return whether or not the window is closed, and that's it.

**Comment by schulzch** [comment]
OK. Maybe I can come up with a less misleading example for the README, but that's out of scope for this bug.
