### ISSUE TITLE
Ensure that OS/X window creation is done in the main thread

### ISSUE THREAD

**Issue by tomaka** [tomaka/glutin#47]
Either fail if not on the main thread, or redirect the creation to the main thread somehow. The second solution is preferred.

cc #4

**Comment by fkaa** [comment]
@DavidPartouche will https://github.com/SSheldon/rust-dispatch enable us to do this?

**Comment by tomaka** [comment]
@SSheldon In my opinion we should just detect whether we're in the main thread when creating a window, and panic if it's not the case.

**Comment by SSheldon** [comment]
@tomaka there's also an issue that we can't poll for events on multiple threads; that should probably just be handled by the main thread.

> While the Application Kit continues to work if other threads are involved in the event path, operations can occur out of sequence. For example, if two different threads are responding to key events, the keys could be received out of order. By letting the main thread process events, you achieve a more consistent user experience. Once received, events can be dispatched to secondary threads for further processing if desired.

I think that, with the current event iterators, another window's iterator might receive your event and then it doesn't know what to do with it.

This could potentially be solved by the main thread polling for events and then dispatching them to the appropriate window. That's where my suggestion of a `glutin_main` came from. Would a requirement that users must call `glutin_main` at the end of their main method make sense in other APIs besides Cocoa?

**Comment by tomaka** [comment]
Closing in favor of https://github.com/tomaka/winit/issues/31
