### ISSUE TITLE
`wait_events()` on X11 burns CPU after failing to process MappingNotify event

### ISSUE THREAD

**Issue by kevinmehall** [tomaka/glutin#471]
Steps to reproduce:
1. `cargo run --example window` (or any app that will stay blocked in `wait_events` and use no CPU)
2. Suspend and resume the laptop, or switch to a virtual terminal and back (ctrl-alt-F1, ctrl-alt-F7)
3. Observe CPU usage of the program

Ubuntu 15.04, Gnome 3.14.4, Intel Haswell Graphics

Poking at it with GDB, and the loop includes:
1. [`XPeekEvent`](https://github.com/tomaka/glutin/blob/1377f276b7b64a1e75aa43da7efdea9a81155397/src/api/x11/window.rs#L269) finds an event with type 34 == [`MappingNotify`](https://github.com/Daggerbot/x11-rs/blob/cb7aa1a7daf9ed50bacc2466e0da722c128c7ac4/src/xlib.rs#L2665).
2. [`XCheckMaskEvent`](https://github.com/tomaka/glutin/blob/1377f276b7b64a1e75aa43da7efdea9a81155397/src/api/x11/window.rs#L118) and [`XCheckTypedEvent`](https://github.com/tomaka/glutin/blob/1377f276b7b64a1e75aa43da7efdea9a81155397/src/api/x11/window.rs#L121) return 0, and the event is never processed.

My only knowledge of the X11 APIs comes from Googling these functions debugging this, but it seems like it might be more robust to use `XNextEvent` instead of `XPeekEvent` so that events can't get left in the queue like this?

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/42
