### ISSUE TITLE
Context Switching with Custom GL Bindings

### ISSUE THREAD

**Issue by Binero** [tomaka/glutin#499]
I like to use the StructGenerator from the gl-rs bindings, as they provide more safety. (also I thought everyone agreed that global variables are pure evil - anyway) Is there a way I can get the `make_current()` function to consume my current context structure, and return a new one?

**Comment by Binero** [comment]
Seems like the main issue here is that glutin doesn't associate the windows with an OpenGL context.

**Comment by tomaka** [comment]
I don't really understand what you're asking.
Each `Window` struct in glutin corresponds to a window + an OpenGL context. Calling `make_current` tells the system that the context of this window is the destination for your OpenGL commands.

**Comment by tomaka** [comment]
We debate this on IRC.
I was leaning against this idea, but even if it was something desirable it would be impossible to implement without adding a template parameter to the `Window` and `HeadlessContext`, which would make the library annoying to use.
