### ISSUE TITLE
Glutin does not show on GTX780 and Kubuntu 15.04

### ISSUE THREAD

**Issue by stevenkucera** [tomaka/glutin#506]
Thanks for glutin, I have it running fine on Windows 8.1

On Kubuntu 15.04 x64 and 16 GB of RAM, with an nVidia GTX70 card the window comes up properly but only displays the background colour. Nothing else draws. This happens in the examples and my own game. All the events are processed properly there is just no display. I have tried both nVidia and Nouveau drivers, and all the opengl display options.

Also if I try the fullscreen example, glutin spits the dummy with: OsError("Could not find a suitable graphics mode")

Steve

**Comment by tomaka** [comment]
The OpenGL commands used by glutin's examples are old OpenGL 1.1 stuff that are maybe no longer supported. Are you using a library in your game or are you manually using OpenGL?

For the fullscreen problem, it should be fixed by #504

**Comment by stevenkucera** [comment]
OK I had 2 errors, 1 my GLSL code was wrong for the new platform, and second one I believe is an error in "src/api/x11/window.rs"

Line 379 tries to find the supported display sizes available, testing it, showed it gets the width right, but the height is always returned as 0. So there is a problem with the foreign function call. I was able to plug this gap by setting best_mode to 0 manually, as I don't know how the inner libraries help. Hope this helps finding the problem.

Steve

**Comment by tomaka** [comment]
> Line 379 tries to find the supported display sizes available, testing it, showed it gets the width right, but the height is always returned as 0. So there is a problem with the foreign function call. I was able to plug this gap by setting best_mode to 0 manually, as I don't know how the inner libraries help. Hope this helps finding the problem.

Yeah I spent two hours on exactly this problem yesterday :smiley: 
That's what #504 fixes

**Comment by ruabmbua** [comment]
Should that issue be closed then?
