### ISSUE TITLE
No keyboard input in fullscreen mode on X11

### ISSUE THREAD

**Issue by tomaka** [tomaka/glutin#509]
When starting the program from a terminal, the keyboard input goes to the terminal instead.
Happens only in fullscreen mode.

**Comment by robertknight** [comment]
I can take a look into this

**Comment by rsaarelm** [comment]
Should #148 and this be merged?

**Comment by tomaka** [comment]
@rsaarelm Yes!
The examples should quit when the escape key is pressed, so as soon as input is fixed it will be possible to exit the fullscreen example.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/45
