### ISSUE TITLE
Slow crate builds

### ISSUE THREAD

**Issue by robertknight** [tomaka/glutin#512]
Hacking on glutin is currently a little painful due to slow builds. This is due to a combination of:
- build.rs regenerating the Rust code for the bindings from the XML sources on every build.
- The generated bindings being fairly large.
- Several of the dependencies use non-absolute version numbers, so Cargo does a refresh on every build in case something changed.

That last bullet point is something that should really be fixed in Cargo itself. My provisional thought for the first two items was to put the bindings into a separate sub-crate but have Glutin re-export all of the sub-crates' contents, so there would be no change in the public API. Thoughts?

**Comment by ZeGentzy** [comment]
Dupe #1050
