### ISSUE TITLE
Memory usage increasing over time in OS X

### ISSUE THREAD

**Issue by tioover** [tomaka/glutin#514]
In OS X glutin program memory usage slow increasing over time. (example [1](https://github.com/tomaka/glium/blob/master/examples/teapot.rs) [2](https://github.com/PistonDevelopers/piston-examples/blob/master/src/sprite.rs))
especially when shaking the mouse memory usage will increase rapidly.

![](http://ww4.sinaimg.cn/mw1024/62c1e01egw1etqpmb6gl4j20t40t0ta2.jpg)

![](http://ww1.sinaimg.cn/mw1024/62c1e01egw1etqpmaatijj20tq0ti3zs.jpg)

[reddit post](https://www.reddit.com/r/rust_gamedev/comments/3c2us6/newbie_quesion_this_is_a_memory_leak/)

**Comment by SSheldon** [comment]
During one of these spikes, I'm seeing a lot of NSEvents allocated and never deallocated:
<img width="892" alt="screen shot 2015-07-20 at 12 07 19 am" src="https://cloud.githubusercontent.com/assets/478311/8771232/a98171ee-2e73-11e5-815f-67cb4de44af4.png">

Looks like this is from `nextEventMatchingMask_untilDate_inMode_dequeue_`, but all the retains seem to be paired with an autorelease:
<img width="1026" alt="screen shot 2015-07-20 at 12 09 33 am" src="https://cloud.githubusercontent.com/assets/478311/8771239/c34439a4-2e73-11e5-8f6a-9f2d111ceee6.png">

Is an autorelease pool ever set up? If anything autoreleased is leaking, that would explain it...
