### ISSUE TITLE
Allow the user to manually choose the pixel format from a list

### ISSUE THREAD

**Issue by tomaka** [tomaka/glutin#517]
Let's say that you want to use multisampling only if the color bits are equal to 32, but you would also accept a format with neither multisampling nor 32 color bits as a fallback.
This is currently not possible with glutin.

In addition to this, the `strict` system is unclear and a bit weird. The whole system is unprecise. You don't really know what it's doing under the hood.

It would be beneficial if the user had a way to manually choose from the list of available pixel formats.

**Comment by tomaka** [comment]
I have a critical question: is it possible to enumerate the list of supported pixel formats on OS/X?

cc @fkaa @SSheldon

**Comment by SSheldon** [comment]
@tomaka, sorry, I don't know anything about OpenGL! Did find this though:

> If the system can't find at least one pixel format that satisfies the constraints specified by the attribute array, it returns NULL for the pixel format object. In this case, your application should have an alternative that ensures it can obtain a valid object.

> One alternative is to set up your attribute array with the least restrictive attribute first and the most restrictive attribute last. Then, it is fairly easy to adjust the attribute list and make another request for a pixel format object.

From the [OpenGL Programming Guide for Mac](https://developer.apple.com/library/mac/documentation/GraphicsImaging/Conceptual/OpenGL-MacProgGuide/opengl_pixelformats/opengl_pixelformats.html), section "Ensuring a Valid Pixel Format Object".

**Comment by tomaka** [comment]
I'm going to close this as "not possible".
