### ISSUE TITLE
EXC_BAD_INSTRUCTION in poll_events() on OSX

### ISSUE THREAD

**Issue by dgopstein** [tomaka/glutin#518]
I have a simple glium program with a `for event in display.wait_events()` loop that very reproducibly fails in the `wait_events()` function when I feed arbitrary mouse input.

I tracked down the error to this OS call in the definition of `PollEventsIterator::next()` in `src/api/cocoa/mod.rs`:
```rust
let event = NSApp().nextEventMatchingMask_untilDate_inMode_dequeue_(
                NSAnyEventMask.bits(),
                NSDate::distantPast(nil),
                NSDefaultRunLoopMode,
                YES);
```

In `lldb` I get the following information:
```
Process 39534 stopped
* thread #1: tid = 0x96a7d7, 0x00007fff87ab5e34 libsystem_platform.dylib`_os_lock_corruption_abort, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x00007fff87ab5e34 libsystem_platform.dylib`_os_lock_corruption_abort
libsystem_platform.dylib`_os_lock_corruption_abort:
-> 0x7fff87ab5e34:  ud2

libsystem_platform.dylib`_spin_lock:
   0x7fff87ab5e36:  movl   $0xffffffff, %ecx
   0x7fff87ab5e3b:  xorl   %eax, %eax
   0x7fff87ab5e3d:  lock
```

**Comment by dgopstein** [comment]
Upon further investigation, this error consistently appears on the 228'th call to `PollEventsIterator::next()`

**Comment by fkaa** [comment]
OS Version? From initial googling it seems it might be related to doing ui-stuff on secondary threads, are you sure your program is as simple as can be? Do any of the other glium or glutin examples work correctly?

**Comment by dgopstein** [comment]
Upon even further investigation this issue is being triggered by another module using an FFI to C. I will continue investigating, and report back, but I don't really know exactly what I'm looking for.
