### ISSUE TITLE
Destroying a win32 window doesn't always stop the window thread

### ISSUE THREAD

**Issue by tomaka** [tomaka/glutin#52]
...which leads to the program continuing to run even when the `main` function has finished.

**Comment by ethan-tqa** [comment]
here is how to prevent it from happening from within the application that is using glutin:

    while !window.is_closed() {
        let mut lol = window.wait_events();
		
		loop {
			match lol.next() {
				Some(x) => {
				},
				None => { break }
			}
		}

        // draw

        window.swap_buffers();
    }

Notice the loop, even though it does nothing here, it is calling next on the WaitEventsIterator object, which in turn processes the events, including Close. That is the point where is_closed will become true. Suggestion to fix this bug: have a special path to handle Close.

There is another thing that I noticed, but not sure about is that you are waiting for WM_DESTROY message. It appears that glfw uses WM_CLOSE. However i tried both and they are both caught when I close the window by pressing the X button.

**Comment by tomaka** [comment]
Thanks.

In my opinion the best fix is to remove this `is_closed` flag and call `GetWindowPlacement` in the `is_closed()` function.

The difference between "destroy" and "close" is that close only hides the window. You can for example hide the window then show it again later, in which case you must only "close" it. Destroying is permanent. Anyway it doesn't really matter as glutin doesn't provide a way to do that.

**Comment by ethan-tqa** [comment]
I'm afraid using GetWindowPlacement could potentially make the check expensive, as it usually placed in the game loop. The idea of using something like is_closed is good, it's just that it must be set correctly based on events. Another possible solution is to have one function that processes all events, which is to be called every frame, and let user provide a callback function. This is how glfw works. Another issue that has not been addressed is low latency input a.k.a raw input. Processing events per frame might cause input lags which is unacceptable in certain games

**Comment by francesca64** [comment]
I'd be shocked if this is still relevant.
