### ISSUE TITLE
Meaning of Event::Closed not clear

### ISSUE THREAD

**Issue by lschmierer** [tomaka/glutin#520]
As far as I understood the Event::Closed event is fired when the user attempts to close the window (e.g. presses the Close (x) button of the window). At least thats the behaviour during my testing under X11.

The docs (and the name) meanwhile give the impression that the event actually is fired after the window really has been closed.

```
    /// The window has been closed.
    Closed,
```

If the window should be closed directly, what is the way to catch `ShouldClose` like events?

**Comment by tomaka** [comment]
The event is reported after the window has been closed.
There's no way to detect when the user clicks on the 'X' and prevent the window from closing.

**Comment by lschmierer** [comment]
So, in my opinion that would be beneficial feature like it is possible in e.g. GLFW.

**Comment by darkstalker** [comment]
Relevant to this, here is something I found while testing stuff under OSX. There it works as an actual ShouldClose event, so clicking the close button doesn't actually close the window and you have to break the event loop manually. But on Linux it unconditionally closes the window. Clearly there is an inconsistency here, and imho it should just send the close event but don't destroy the window, so you get a chance to display those "save? yes/no/cancel" dialogs. Gtk can do it under linux, so it should be possible.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/46
