### ISSUE TITLE
Compilation on 64bit Windows fails

### ISSUE THREAD

**Issue by raleksandar** [tomaka/glutin#526]
Compiling glutin on 64bit Windows 8.1 results in bunch of mismatched type errors:

````
src\api\win32\event.rs:12:9: 12:24 error: mismatched types:
 expected `u64`,
    found `i32`
(expected u64,
    found i32) [E0308]
src\api\win32\event.rs:12         winapi::VK_BACK => Some(VirtualKeyCode::Back),
                                  ^~~~~~~~~~~~~~~
````
Reason for this is that `WPARAM` is 64bit on 64bit Windows and `VK_*` constants are defined as `c_int` in winapi crate.

Truncating `code` parameter in `vkeycode_to_element` function (`src/api/win32/event.rs`) to 32 bits allows for compilation to succeed (despite some unused_variables, unused_unsafe and dead_code warnings).

I'm not sure if this should be fixed in gluten (i.e. simply truncating variable) or in winapi?

**Comment by tomaka** [comment]
Should be fixed by #529
