### ISSUE TITLE
Mouse click events are sent twice on X11

### ISSUE THREAD

**Issue by tomaka** [tomaka/glutin#533]
cc @robertknight 

I don't actually know which events are received twice, but I noticed something wrong in my game after switching to the latest version of glutin.
Haven't investigated yet.

**Comment by robertknight** [comment]
I'm taking a look

**Comment by robertknight** [comment]
This also appears to apply to other XInput events as well, based on the XGenericEventCookie::serial property of the returned events, its just less obvious with mouse move events.
