### ISSUE TITLE
Example "multiwindow" does not close on OSX

### ISSUE THREAD

**Issue by bvssvni** [tomaka/glutin#544]
It seems that the close button in the corner is not activated when hovering the mouse button over it. I can't press the button but get a color wheel instead.

**Comment by paulrouget** [comment]
Do you use osx 10.11?

**Comment by bvssvni** [comment]
OSX 10.9.5.

**Comment by fkaa** [comment]
Same on 10.10.2

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/48
