### ISSUE TITLE
Mouse button input hardly works on Mac

### ISSUE THREAD

**Issue by dylanede** [tomaka/glutin#557]
I've started work on [cef-rs](https://github.com/dylanede/cef-rs) again, and now that I've updated everything to the latest Rust nightly and library versions, I've discovered a regression since I last used Glutin mouse input 6 months ago. Currently, although mouse movement input works (though now it seems to be reporting mouse movement events when the mouse moves anywhere on the screen, not just on the window, resulting in sometimes negative mouse coordinates), mouse button input is broken. The only mouse click event I can get to show up is releasing the left mouse button, sometimes. This is simply from a for loop on `display.poll_events()`. Any ideas what might have broken this?

**Comment by dylanede** [comment]
Having said that, I now realise that it may in fact be the case that mouse button input never worked on Mac - the last time I used mouse button input was on Windows.

**Comment by bvssvni** [comment]
Mouse button input works ok on OSX 10.9.5. Could you try the "user_input" example and see if there is a difference between Glutin and SDL2 on your computer? https://github.com/pistondevelopers/piston-examples/

**Comment by jaredpetker** [comment]
I'm also seeing mouse input working pretty poorly for osx (10.10.4). Mouse moving is the most reliable, but it definitely will start dropping events at times, mouse down / up barely work, once in a while I'll get a mouse down / mouse up, and I don't think I've ever gotten it to work in a pair of mouse down / mouse up occurring one after another.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/51
