### ISSUE TITLE
Control, shift and alt key events return None virtual key code on Windows

### ISSUE THREAD

**Issue by dylanede** [tomaka/glutin#559]
Other keys that do this include the tilde key and the minus and equals keys next to the number row.

Having the modifier keys return None is stopping cef-rs from being able to track modifiers and send key-combo commands (like Ctrl-A, etc.).

It would also be handy to be able to query the state of a key from Glutin, but that should probably be another issue.

**Comment by viperscape** [comment]
I confirmed I am using ```glutin v0.3.5``` from Crates.io but still do not see Release or Press keycode events for Control,shift,alt. I'm on Windows 10
