### ISSUE TITLE
Add mouse enter/leave events

### ISSUE THREAD

**Issue by bvssvni** [tomaka/glutin#570]
This is a requested feature when you are dragging something and the cursor moves outside the window. On Linux and Windows the window stops emitting mouse coordinates. When returning to the window this can lead to undesirable behavior.

See https://github.com/PistonDevelopers/piston/issues/958 for discussion.

**Comment by bvssvni** [comment]
@cybergeek94 you mentioned that only leave events could be added in WinAPI. Is this right?

**Comment by cybergeek94** [comment]
As far as I can tell, yes. There's [`WM_MOUSELEAVE`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms645615%28v=vs.85%29.aspx) message but no corresponding `MOUSEENTER` message.

It looks like a mouse-entered message is supposed to be implied when you start getting `WM_MOUSEMOVE` messages again after `WM_MOUSELEAVE`: http://blogs.msdn.com/b/oldnewthing/archive/2003/10/13/55279.aspx

**Comment by darkstalker** [comment]
On Linux, X11 generates both events natively: https://tronche.com/gui/x/xlib/events/window-entry-exit/

**Comment by vberger** [comment]
Wayland does natively generate both as well: http://vberger.github.io/wayland-client-rs/wayland_client/wayland/seat/enum.WlPointerEvent.html

**Comment by AndyBarron** [comment]
I'm going to take a stab at this.

I'm thinking of adding a `MouseLeft` event and letting `MouseMoved` imply it re-entered on all platforms. `MouseWindow(bool)` is cleaner, but kind of a pain in Windows...

Thoughts?

**Comment by AndyBarron** [comment]
The more I think about it, the more I like leaving `MouseLeft` as its own event. It avoids getting two events (e.g. `MouseWindow(true)` and `MouseMoved(x, y)`) when the mouse *enters* the window.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/53
