### ISSUE TITLE
  Problem enable sRGB

### ISSUE THREAD

**Issue by Yamakaky** [tomaka/glutin#581]
``` rust
// building the display, ie. the main object
let display = glutin::WindowBuilder::new()
        .with_title(format!("Snake 3D effect"))
        .with_srgb(Some(true))
        .build_glium();
assert_eq(display, Err(BackendCreationError(NoAvailablePixelFormat)));
```

I have an intel HD3000 on ArchLinux/x11. Any idea ?

**Comment by tomaka** [comment]
Copy-pasting from the other issue:

> It's also a known problem on Linux (are you on Linux?). For some reason the GLX & EGL implementations always report sRGB as false, even when the formats actually have sRGB enabled.

The solution is simply to not call `with_srgb`. You will probably still get sRGB enabled.

It's still an active problem though.

**Comment by ZeGentzy** [comment]
https://github.com/tomaka/glutin/issues/952#issuecomment-467228004
