### ISSUE TITLE
Implement `Touch` events for OSX

### ISSUE THREAD

**Issue by mitchmindtree** [tomaka/glutin#592]
Seems that [`Touch`](https://github.com/tomaka/glutin/blob/master/src/events.rs#L79) events are yet to be implemented for OSX.

**Comment by paulrouget** [comment]
Cocoa reference: https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/EventOverview/HandlingTouchEvents/HandlingTouchEvents.html

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/54
