### ISSUE TITLE
Hiding cursor on x11

### ISSUE THREAD

**Issue by ryndinol** [tomaka/glutin#594]
Is there already an implemented way to hide the mouse cursor on x11?

Currently I'm generating an empty cursor when window.set_cursor(MouseCursor::NoneCursor) is called:
1383010

**Comment by est31** [comment]
This seems to be fixed by 267221af3e239c79a2617c46ba3f1259663c29f7 , although window.set_cursor(NoneCursor) is not implemented atm.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/55
