### ISSUE TITLE
Splitting up OpenGL Context handling to a seperate crate

### ISSUE THREAD

**Issue by Binero** [tomaka/glutin#599]
This crate seems to have pretty good OpenGL context support through the [GlContext](https://github.com/tomaka/glutin/blob/9d6d2412c7fc7c26574e91a8dc981eaecaa49542/src/lib.rs#L81) trait. I think it'd be a good idea to split this part of Glutin (including the APIs like WGl and Mesa) to a different crate.

My motivation for this is that this part of OpenGL is OS specific and not specific to a window handling library. This would allow any library providing a GL-rendering canvas to easily load in functions without writing the same platform specific code. A good example of when this could be useful is when using a GTK `GtkGlArea`.

The reason I crate an issue for this instead of just creating my own project is for the exact same motivation that I think this should happen in the first place. To avoid redundant code.

**Comment by tomaka** [comment]
I'm not sure to understand. `GtkGlArea` creates the OpenGL context for you, so why would extracting the context creation functions be useful in this case?

**Comment by Binero** [comment]
The most interesting functionality would be the handling of the context, for example retrieving the function pointers.

**Comment by tomaka** [comment]
GTK already uses WGL/GLX/EGL/etc.
I don't know why they aren't providing a wrapper for `GetProcAddress`.

**Comment by Binero** [comment]
The idea is to have a crate that unifies all of those to have a standard way to create and or handle these contexes.
