### ISSUE TITLE
Fullscreen example is broken on OS X

### ISSUE THREAD

**Issue by jdm** [tomaka/glutin#620]
The terminal shows:

```
godot2:glutin jdm$ cargo run --example fullscreen
     Running `target/debug/examples/fullscreen`
Monitor #0: Some("Monitor #40985")
```

but nothing appears on the screen.

**Comment by adambadawy** [comment]
You most likely didn't see the prompt to choose a monitor because it wasn't being flushed. I've made a PR (#645) fixing this.

**Comment by tomaka** [comment]
I'm going to close for https://github.com/tomaka/glutin/pull/645 I guess.
