### ISSUE TITLE
Support keypress events with non-ascii chars

### ISSUE THREAD

**Issue by est31** [tomaka/glutin#625]
Some people want to play games on non-ascii keyboard layouts. Sometimes, even the popular WASD keys can be bound to such chars, like with the Swedish Dvorak layout called Svorak. It would be great if you would get a way to let users with these layouts use their layout not just for things like chatting/setting their name/nick, but also for ingame movement.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/59
