### ISSUE TITLE
Headless rendering on OSX/Cocoa not working

### ISSUE THREAD

**Issue by FredrikNoren** [tomaka/glutin#635]
Right now it gives an error `version '150' is not supported` because it's using the legacy version of OpenGL. Adding this:

```rust
NSOpenGLPFAOpenGLProfile as u32, NSOpenGLProfileVersion3_2Core as u32,
```

to https://github.com/tomaka/glutin/blob/master/src/api/cocoa/headless.rs#L39 takes it a bit further; the shaders will load and run. However I can't get it to actually render anything: the rendered image is just a blank image of whatever you put in `gl::ClearColor`, but no geometry shows up.

I've tried a bunch of variations for the `attributes` but none of them have made any difference.

I also tried switching the framebuffer code in https://github.com/tomaka/glutin/blob/master/src/api/cocoa/headless.rs#L70 to:

```rust
let mut renderbuffer: u32 = 0;
//Set up a FBO with one renderbuffer attachment
gl::GenFramebuffersEXT(1, &mut framebuffer);
gl::BindFramebufferEXT(gl::FRAMEBUFFER_EXT, framebuffer);
gl::GenRenderbuffersEXT(1, &mut renderbuffer);
gl::BindRenderbufferEXT(gl::RENDERBUFFER_EXT, renderbuffer);
gl::RenderbufferStorageEXT(gl::RENDERBUFFER_EXT, gl::RGBA8, 1024, 768);
gl::FramebufferRenderbufferEXT(gl::FRAMEBUFFER_EXT, gl::COLOR_ATTACHMENT0_EXT,
                 gl::RENDERBUFFER_EXT, renderbuffer);
let status = gl::CheckFramebufferStatusEXT(gl::FRAMEBUFFER_EXT);
if status != gl::FRAMEBUFFER_COMPLETE_EXT {
    panic!("Error while creating the framebuffer");
}
```

which I believe is closer to what is specified in https://developer.apple.com/library/mac/documentation/GraphicsImaging/Conceptual/OpenGL-MacProgGuide/opengl_offscreen/opengl_offscreen.html, but it doesn't seem to make a difference.

The way I'm reading out the data is through:
```rust
e: Vec<u8> = vec![0; 1024 * 768 * 4];
gl::ReadPixels(0, 0, 1024, 768, gl::RGBA, gl::UNSIGNED_BYTE, value.as_mut_ptr() as *mut GLvoid);
let image = RgbaImage::from_raw(1024, 768, value).unwrap();
image.save(Path::new("test.png"));
```
(using the piston image library).

Any suggestions and ideas appreciated, would be really cool to get this working!

**Comment by FredrikNoren** [comment]
I've also tried different variations of `gl::ReadBuffer` (though I'm pretty sure it should be `gl::ReadBuffer(gl::COLOR_ATTACHMENT0);`).

**Comment by FredrikNoren** [comment]
This article talks about how to accomplish it: http://renderingpipeline.com/2012/05/windowless-opengl-on-macos-x/

I've tried the exact attributes he's using, but they don't seem to help

**Comment by tomaka** [comment]
Under no circumstances glutin should call OpenGL functions. That code should be changed.
