### ISSUE TITLE
transparent example does not work on Arch Linux with X11 and Intel driver

### ISSUE THREAD

**Issue by mystal** [tomaka/glutin#639]
I am using compton as my compositor, yet the window background is solid black:
![2015-10-15-094630_1440x900_scrot](https://cloud.githubusercontent.com/assets/74258/10520897/abb733de-7321-11e5-9934-a5807b954f60.png)

The reported pixel format is:

```
Pixel format of the window: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, double_buffer: true, multisampling: None, srgb: false }
```

And OpenGL version:

```
OpenGL version 3.3 (Core Profile) Mesa 11.0.3
```

Any ideas?

**Comment by mystal** [comment]
So the good news is that it *used* to work. PR #484 added transparency, so I checked out the repository at that commit (e48c853b9c7a617bf8ba5f31b5fb2088c90c0ee7) and it worked!

I'm not familiar enough with X11 or Glutin to figure this out, unfortunately...

**Comment by tomaka** [comment]
The culprit is most likely the code that changed how pixel formats were selected.
