### ISSUE TITLE
keyboard inputs repeat while held down? is there a way to get notified of changes only?

### ISSUE THREAD

**Issue by DanielCollins** [tomaka/glutin#641]
Not sure if this is a bug or working as intended or me doing something wrong. Couldn't find any mention of it in documentation.

I am doing `for ev in window.poll_events()` then matching `a` and `b` in `glium::glutin::Event::KeyboardInput(a, _, b)` against `(glium::glutin::ElementState::Pressed, Some(glium::glutin::VirtualKeyCode::Space))`.

I expected to see it only once per keypress (which would also be more convenient in my specific use case), but it recurs. Haven't attempted to measure how often. Every call to `poll_events()`?

On Arch Linux, X11.

**Comment by tomaka** [comment]
In any application (like a text editor or your browser) when you maintain a key on your keyboard, after a few hundredths of a second the character starts repeating. That's the same happening here.
It's the operating system or the compositor that does this, not glutin. Glutin just transfers the messages that are sent to it.

**Comment by DanielCollins** [comment]
okay, thank you. just didn't match my mental model. seems like a waste of effort on the part of the operating system/compositor to me. i suppose it helps a consistent hold-down-key typing speed across applications. could possibly be added to documentation? anyway i will just deduplicate the stream manually.
