### ISSUE TITLE
Run window without console prompt being still open

### ISSUE THREAD

**Issue by Syrou** [tomaka/glutin#649]
Not an issue per se, but, once you have a glutin window up and use glium to draw something in it, i'd like to only show that window, not the console too. Is this possible to remove the console prompt somehow, while having the glutin window still running?

**Comment by adambadawy** [comment]
This is kind of a logistics thing with how programs work in general. If you run Google Chrome from a terminal, and close the terminal, Chrome will close with it. What OS are you on? On Linux you can run your program like so and safely close the terminal:

```
nohup target/debug/program_name &
```

The above assumes the following:
* You're in the same directory as `Cargo.toml`
* You're doing a debug build (default when you do `cargo build`)
* Your crate is named `program_name` (not likely)

**Comment by Syrou** [comment]
I'm on Windows. It seems weird to me this is something you should not be able to specify when you build. But then again my first day using rust and dabbling with opengl

**Comment by tomaka** [comment]
On Windows this is handled by a flag in the executable's headers. Therefore you have to pass an option to the linker.

In practice, for the moment I think you can make it work by creating a small .bat script that calls `gcc` and passes the -mwindows` flag. That's for the MinGW version of Rust. For the MSVC version of Rust the flag is different.

cc @retep998 who may have a example

**Comment by Syrou** [comment]
Found this: http://stackoverflow.com/questions/29763647/how-to-make-a-program-that-does-not-display-the-console-window/29764309#29764309 meanwhile. Seems like there has been an active discussion in this thread: https://github.com/rust-lang/cargo/issues/544

on the subject too

**Comment by retep998** [comment]
`cargo rustc -- -Clink-args="/SUBSYSTEM:WINDOWS"` along with providing the equivalent entry point since Rust only handles the console entry point.

**Comment by Revertron** [comment]
@Syrou I've just added a full answer how to build a windows app without console window in that SO question.

**Comment by tomaka** [comment]
An RFC for this has recently been accepted: https://github.com/rust-lang/rfcs/pull/1665
Here is the tracking issue that you should follow to know when it's implemented: https://github.com/rust-lang/rust/issues/37499
