### ISSUE TITLE
kernel32-sys conflict

### ISSUE THREAD

**Issue by mitchmindtree** [tomaka/glutin#656]
```
$ cargo build
native library `kernel32` is being linked to by more than one package, and can only be linked to by one package

  kernel32-sys v0.2.0
  kernel32-sys v0.1.4
```

I'm unable to test this as I don't have a windows system available to me, however the fix might just be to change `kernel32-sys = 0.1` to `kernel32-sys = 0.2` under each of the windows targets?

**Comment by retep998** [comment]
This should be fixed by doing a simple cargo update as `kernel32-sys = 0.2.1` fixed this.

**Comment by tomaka** [comment]
I'm going to close this. Please reopen if it's still an issue.
