### ISSUE TITLE
Second field of Event::KeyboardInput(..) is undocumented

### ISSUE THREAD

**Issue by HeroesGrave** [tomaka/glutin#662]
It's just a `u8` with no description or even field name.

In fact, the docs for the `Event` enum are overall rather lacking.

`ReceivedCharacter` is another one that sticks out as mysterious. Under what circumstances does that event get fired? How does it relate to the `KeyboardInput` event being fired? etc.

**Comment by Kasran** [comment]
I can at least say that the `u8` field of `KeyboardInput` is the scan code of the key for which the event is being reported, which you can use to identify the key being pressed even when the third field is `None` (so you can't check what key it is by its `VirtualKeyCode`). (I think in current documentation it's labeled as a `ScanCode`, but there's still no explanation for it past that.)

I'm also wondering about `ReceivedCharacter`, though.

**Comment by LFalch** [comment]
`ReceivedCharacter` is the character that you have typed. For instance, if you held shift and pressed H, you'd get a capital H. Basically, it's like what you'd get, if you were typing into a textbox.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/61
