### ISSUE TITLE
Multithreading discussion

### ISSUE THREAD

**Issue by tomaka** [tomaka/glutin#67]
Let's sum up everything related to multithreading.
## API limitations
- In win32, you can create windows in any thread (not only in the main thread contrary to popular belief), but in order to retreive the window's events you must call `GetMessage` in the same thread as the one where you create the window.
- In xlib, you must call `XInitThreads` before any other xlib function, or the library is not thread-safe.
- In cocoa, apparently everything must be done in the main thread. I don't know much about cocoa, so someone should bring some more informations.
## What do other libraries do?

GLFW and the SDL just assume that you do everything in the main thread. GLFW calls `XInitThreads` but the SDL does not.

_Needs more informations here_
## What does glutin do?
- In win32, a new thread is created for each window and messages are passed through channels.
- In xlib, `XInitThreads` is called behind a `Once` (https://github.com/tomaka/glutin/pull/65).
- In cocoa, as far as I know the implementation is currently unsafe (@DavidPartouche is working on it)

**Comment by ZeGentzy** [comment]
iOS allows multithreading, afaik: https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/ConcurrencyandOpenGLES/ConcurrencyandOpenGLES.html, just need to make_not_current the context before sending it.
