### ISSUE TITLE
Force Touch causes weird behavior

### ISSUE THREAD

**Issue by cptroot** [tomaka/glutin#672]
Using the force touch behavior on my apple trackpad causes ups and downs to no longer be in sync.

**Comment by cptroot** [comment]
I did some messing around with the base glutin to try and diagnose when it happens. As part of this, I discovered that in addition to getting LeftMouseDown and LeftMouseUp events, the app is getting SystemDefined events, subtype 7. These SystemDefined events stop after messing with it for a while, and that's where the odd behavior begins.

The odd behavior consists of occasional duplicated or missing pressed or released events, and the app not hovering over the upper left corner (x does not appear on close button).

I don't currently have a guaranteed repro, other than randomly clicking until the SystemDefined events stop occurring. Clicking out may or may not increase the frequency of this happening.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/63
