### ISSUE TITLE
[Linux] Multiple monitors identified as a single one

### ISSUE THREAD

**Issue by StelarCF** [tomaka/glutin#678]
I have this issue in [this game](http://ludumdare.com/compo/ludum-dare-34/?action=preview&uid=61710). In it, the issue manifests as a bug where you cannot point anywhere to the right, only (at best) up/down and to the left no matter where you move the mouse, unless I make the window as big as both of my screens. After inspecting the source code, I _think_ I have narrowed it down to [both of my monitors being identified as a single one](https://github.com/Benjamin-L/ld34/blob/master/src/main.rs#L24) - since they are both the same size (1920x1080), when the window only occupies one of them (the main one) it gets the wrong width and height, which produces the aforementioned bug.

**Comment by adambadawy** [comment]
It's common for an X-server to just say there's one screen even if it's outputting to multiple monitors. The implementation of `get_available_monitors` is not correct for X11.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/64
