### ISSUE TITLE
resizability & min/max dimensions

### ISSUE THREAD

**Issue by SenneH** [tomaka/glutin#681]
There didn't seem to be a resizable flag so I tried setting the min and max dimension to the same values as the window dimensions. This didn't seem to give the desired effect. 
with_min_dimensions() & with_max_dimensions() set the dimension _including_ the window border. I don't think this is the desired behavior for most users. 

platform: windows 7

```
    let window = glutin::WindowBuilder::new()
        .with_title("Title".to_string())
        .with_dimensions(720, 480) // set the size excluding the border
        .with_min_dimensions(720, 480) // sets the size including the border
        .with_max_dimensions(720, 480) // sets the size including the border
        .build_glium()
        .unwrap();

```

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/65
