### ISSUE TITLE
[feature request] Backend selection

### ISSUE THREAD

**Issue by petevine** [tomaka/glutin#701]
It would be a great idea, mainly from compilation times' point of view, to allow disabling the other linux backend (presently wayland, in the future X11) as wayland is still a completely redundant dependency on some platforms (like arm SBC's for example). What's the story on windows I wonder?

Did I mention compilation times? ;)

**Comment by vberger** [comment]
It should be possible to maybe add two cargo features : `x11` and `wayland`, each activating the associated backend, and both in the default feature set. These would have no effect when on windows or macos.

I guess it's just a matter of putting a few `#[cfg(feature = "...")]` here and there.

What do you think about this design @tomaka ?

**Comment by tomaka** [comment]
Yes.

**Comment by vberger** [comment]
Hmm, apparently cargo features do not yet mix well with cargo targets.

As a result, making these `x11` and `wayland` features would allow to disable/enable their support in glutin, but both would still be pulled as dependencies.

In this context, is it still worth doing it?

**Comment by petevine** [comment]
What's the situation nowadays?

**Comment by genodeftest** [comment]
Did you close this because it is fixed? Or because nobody answered your question?
