### ISSUE TITLE
How do I text?

### ISSUE THREAD

**Issue by SimonSapin** [tomaka/glutin#719]
What’s the proper way to have a box where users can type text? Ideally the application would get Unicode, independently of the user’s keyboard layout and text input method (e.g. IME for east-asian languages).

Servo currently uses `KeyboardInput` events and maps them to characters, but that’s limited to ASCII and hard-wired to a QWERTY layout. `ReceivedCharacter` seems relevant, but it apparently does not provide everything expected: https://github.com/servo/servo/issues/4144#issuecomment-180380273. Is this a bug? Or is there some other API to use?

**Comment by vberger** [comment]
I implemented the wayland backend to correctly handle unicode chars and all (successfully tested with my french keyboard and all sorts of dead keys), so I *hope* it's a bug of the macos backend.

Didn't test, but afaik X11 uses the same lib (libxkbcommon) to handle keymaps, so it should probably behave the same.

**Comment by SimonSapin** [comment]
So `ReceivedCharacter` is the way to go?

**Comment by tomaka** [comment]
Yes `ReceivedCharacter` is what you're supposed to use.

**Comment by paulrouget** [comment]
Followup: https://github.com/tomaka/glutin/issues/721
