### ISSUE TITLE
Full Screen Focus Switch OSX

### ISSUE THREAD

**Issue by MasonRemaley** [tomaka/glutin#720]
I'm having trouble switching focus from a full screen window created using `with_fullscreen` on OSX.

Most full screen OSX apps just take up their own "space", but the window created takes over the space I'm currently in. When I attempt to switch focus using command-tab, the focus switches without hiding the window so my view of whichever application I've switched into is obstructed.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/66
