### ISSUE TITLE
ReceivedCharacter not sent for non ascii characters on osx

### ISSUE THREAD

**Issue by paulrouget** [tomaka/glutin#721]
Typing `é`, for example, doesn't trigger the `ReceivedCharacter` event.

I blame this line: https://github.com/tomaka/glutin/blob/3246613a51568073e40ee99efeb0c76c36db3ecc/src/api/cocoa/mod.rs#L840

**Comment by fkaa** [comment]
@paulrouget that is only one part of the problem. While it will allow you to receive characters created with `shift + alt`, it will ignore composing characters such as `¨ + a -> ä` and IME input.

GLFW ignores this functionality, while SDL2 adds an invisible textfield which has all the normal text input capabilities you'd expect. If we were to replicate that there would have to an API change in the form of `start_text_input()` and ´stop_text_input()´ to tell glutin when the text field should be focused.

**Comment by paulrouget** [comment]
> that is only one part of the problem

Absolutely. But it's still an improvement.

I'll file an issue for composed characters.

**Comment by fkaa** [comment]
>But it's still an improvement.

Agreed! Kind of curious how that line got there in the first place..

**Comment by fkaa** [comment]
Fixed in #722.
