### ISSUE TITLE
Event::Moved isn't working

### ISSUE THREAD

**Issue by darkstalker** [tomaka/glutin#724]
Moving the window around isn't triggering Event::Moved. Tested with glutin 0.4.8 under Linux/X11 and OSX.

test code: https://gist.github.com/darkstalker/d83872cea9d828a591d6

**Comment by vberger** [comment]
Just as a side note: this won't be fixeable for the wayland backend. By design wayland client do not know nor control the location of their windows on the screen.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/67
