### ISSUE TITLE
Vulkan support

### ISSUE THREAD

**Issue by bitshifter** [tomaka/glutin#726]
I noticed that GLFW now supports Vulkan (http://www.glfw.org/docs/3.2/vulkan.html). I don't know if this is planned or already in progress for glutin so I thought I'd raise an issue for visibility.

**Comment by tomaka** [comment]
GLFW wraps around a lot of functionalities of Vulkan.
I think it's a bad design, as GLFW hides a lot of things.

Technically the only thing you need to render to a window using Vulkan is the ID of the window. There's no need to create the window with special flags or things like that.

**Comment by fkaa** [comment]
@tomaka so a flag to skip the GL context entirely would be a solution?

**Comment by bitshifter** [comment]
There's lots of GL specific methods on glutin interfaces like Window, WindowBuilder. Would it make sense to separate Gl specifics from Window even if Vulkan wasn't handled internally by glutin?

**Comment by retep998** [comment]
If the GL specific stuff of glutin was separated out to make it more usable for vulkan, that could be taken advantage of to use glutin for other graphics APIs like DirectX.

**Comment by bitshifter** [comment]
> If the GL specific stuff of glutin was separated out to make it more usable for vulkan, that could be taken advantage of to use glutin for other graphics APIs like DirectX.

That would also be nice!

**Comment by Luke-Nukem** [comment]
> If the GL specific stuff of glutin was separated out to make it more usable for vulkan, that could be taken advantage of to use glutin for other graphics APIs like DirectX.

Seems it would be better to keep the API's to a minimum, and keep the whole library cross-platform.

**Comment by tomaka** [comment]
For the moment the idea would be to split glutin in two:

- `winin` (or whatever the name is) would contain all the window initialization and events handling stuff, and allows extracting the window ID.
- `glutin` lies on top of `winin` and builds an OpenGL context on top of winin's window.

**Comment by retep998** [comment]
That sounds like a good idea, although the name `winin` is kinda weird, doesn't roll off the tongue the way `glutin` does.

**Comment by devnought** [comment]
@retep998 `winin` is close to `winning`, but you could maybe call it `winit`.

**Comment by retep998** [comment]
Also another point is the `win` prefix makes it seem like it has to do with Windows when actually it's just windows.

**Comment by yupferris** [comment]
small 2 cents; `winit` would be a lovely name :)

**Comment by tomaka** [comment]
I'm going to name it `winit` then.

**Comment by tomaka** [comment]
Since glutin receives several design changes, it's difficult to use `git filter-branch` or similar commands.
I guess I'm simply going to create a clone of glutin, rename it, and remove the GL-specific stuff from it.

Then once that's setup and working, submit a PR to glutin to switch to winit.

**Comment by tomaka** [comment]
Created https://github.com/tomaka/winit

**Comment by kvark** [comment]
Doesn't look like this is going anywhere. There is not even a task to port `glutin` to `winit`.
@tomaka what's the situation?

**Comment by tomaka** [comment]
The situation it's that it's painful but not difficult to switch glutin to winit and I don't have time and motivation to do that.

**Comment by tomaka** [comment]
I'm going to close this since glutin now uses winit.

**Comment by kingofoz** [comment]
Hello,
So now glutin supports vulkan?

**Comment by kingofoz** [comment]
@tomaka any comments about my question?

**Comment by kvark** [comment]
@kingofoz `winit` supports Vulkan. Glutin is now `winit` + GL-specific parts. Thus, Glutin support Vulkan no longer makes sense.

**Comment by kingofoz** [comment]
I see. Thanks! @kvark 
Then can you show me an example which is using vulkan?

**Comment by ozkriff** [comment]
https://github.com/vulkano-rs/vulkano-examples ?
