### ISSUE TITLE
Events are broken when opening multiple windows

### ISSUE THREAD

**Issue by darkstalker** [tomaka/glutin#727]
If you open and poll events for multiple windows, they are received by a random window, instead of the one where currently the event is happening. That means if I open two windows called `foo` and `bar`, if I move the mouse inside `foo`, then `bar` will randomly receive mouse movement events too.

Included sample code for both glium and glutin versions: https://gist.github.com/darkstalker/e1059220502a29913752

**Comment by tomaka** [comment]
On which platform is this?

**Comment by darkstalker** [comment]
Linux x86_64, under x11

**Comment by darkstalker** [comment]
This is probably because it's using a function that receives events for all the windows [1] instead of using something like `XCheckWindowEvent` (i guess). Duno how this is handled on other platforms.
Anyway I think this per-window event paradigm is incorrect, since it would require multiple event loops for an app with multiple windows, and doing that requires polling, since `wait_events` blocks. It would be better to have a single `wait_events` loop for the entire application, and the iterator returning a (Window, Event) pair to know where it happened. The current design is "ok" only for single window applications.

[1] https://github.com/tomaka/glutin/blob/master/src/api/x11/window.rs#L184

**Comment by vberger** [comment]
My 2 cents: I had this issue for wayland: the events for the whole application must be retrieved in the same place. So I've set up some global logic for dispatching the events to internal event queues for each window: https://github.com/tomaka/glutin/blob/master/src/api/wayland/context.rs#L152-L188

The caveat of this regarding glutin design, is that `wait_events` will stop blocking at the first dispatched event to any window, and thus can return `None`. Don't know if it is a problem actually...

**Comment by darkstalker** [comment]
This looks like a design flaw in glutin for me. Probably it was designed for single window apps (like games). But I'm trying to write a widget toolkit, and this doesn't fit my needs. Looks like i'll have to fallback to raw Xlib :c

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/68
