### ISSUE TITLE
MouseMoved variant is a (tuple of a tuple of i32) rather than a (tuple of i32)

### ISSUE THREAD

**Issue by RichardlL** [tomaka/glutin#751]
Event::MouseMoved is inconsistent with the other variants, it is 

`
MouseMoved( (i32, i32) )`

rather than
`
MouseMoved(i32, i32)`

like
```
Resized(u32, u32),
Moved(i32, i32),
TouchpadPressure(f32, i64)
```

Forgive me if this came up before,

**Comment by bjz** [comment]
Yes, I've found this a little strange too. Would be great to have some consistency!

**Comment by tomaka** [comment]
Since there is already a breaking change in the events compared to the published version, the change could be made before I publish a new one.
