### ISSUE TITLE
GLX: `CONFIG_CAVEAT`  should be set to `NON_CONFORMANT_CONFIG` when multisampling is requested

### ISSUE THREAD

**Issue by BonsaiDen** [tomaka/glutin#754]
Multisampling FBConfigs are non-conformant and currently only `NONE` is set when `reqs.hardware_accelerated` which causes the `FBConfig` to return `NoAvailablePixelFormat`.

Hacking the `NON_CONFORMANT_CONFIG` into `glx/mod.rs` correctly creates a framebuffer with multisampling enabled:

```       
if let Some(hardware_accelerated) = reqs.hardware_accelerated {
    out.push(ffi::glx::CONFIG_CAVEAT as c_int);
    out.push(if hardware_accelerated {
        ffi::glx::NON_CONFORMANT_CONFIG as c_int
        //ffi::glx::NONE as c_int
    } else {
        ffi::glx::SLOW_CONFIG as c_int
    });
}
```

I'll try to whip up a PR which checks for multisampling tomorrow.

**Comment by Bobo1239** [comment]
Somehow the mesa driver (Intel HD 5500) behaves exactly the other way around and only returns a PixelFormat, when `NON_CONFORMANT_CONFIG ` is __not__ set. After this change, I get a `NoAvailablePixelFormat` error whereas it works flawlessly when `CONFIG_CAVEAT` is set to `NONE`.

Could this be a driver bug or am I understanding the change incorrectly?

**Comment by BonsaiDen** [comment]
Can you post the output of `glxinfo` ?

It should list all available frame buffer configurations along with the `caveat` required for them.

```
    visual  x   bf lv rg d st  colorbuffer  sr ax dp st accumbuffer  ms  cav
  id dep cl sp  sz l  ci b ro  r  g  b  a F gb bf th cl  r  g  b  a ns b eat
----------------------------------------------------------------------------
0x021 24 tc  0  24  0 r  y .   8  8  8  0 .  s  4 24  8 16 16 16 16  0 0 None
...
0x02f 24 tc  0  24  0 r  y .   8  8  8  0 .  s  4 24  0 16 16 16 16  2 1 Ncon
...
```

**Comment by BonsaiDen** [comment]
We might end up needing to use `ffi::glx::DONT_CARE` here instead.

**Comment by Bobo1239** [comment]
[Output of `glxinfo -t`](http://pastebin.com/kcERM9xj)

**Comment by Bobo1239** [comment]
`ffi::glx::DONT_CARE` works on my machine. (with and without multisampling)

**Comment by tomaka** [comment]
Yeah, let's go with `DONT_CARE`.

**Comment by Bobo1239** [comment]
Always `DONT_CARE` or only when multisampling is enabled. (-> Still `NONE` or `SLOW_CONFIG` when no multisampling)

**Comment by tomaka** [comment]
Probably always I'd say. The fact that mainstream implementations don't behave correctly means that you shouldn't even try to do something fancy.
