### ISSUE TITLE
Opening a Window on Windows with LTO panics

### ISSUE THREAD

**Issue by NeoLegends** [tomaka/glutin#756]
https://github.com/tomaka/glium/issues/1446 belongs here, since it is an error within glutin, not glium.

---

Running the `window` example with Link-Time-Optimization on Windows yields the following panic:
```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("CreateWindowEx function failed: Unzul\u{e4}ssiger Zugriff auf einen Speicherbereich. (os error 998)")', ../src/libcore\result.rs:746
stack backtrace:
   0:           0x441b01 - panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::closure.43476
   1:           0x43aec8 - sys_common::unwind::begin_unwind_inner::h5d88fc2c0dc01c2fDet
   2:           0x43d56c - sys_common::unwind::begin_unwind_fmt::h19b46af24ca895c4Jdt
   3:           0x4486eb - rust_begin_unwind
   4:           0x449ec7 - panicking::panic_fmt::h8637277b55628ae7XVL
   5:           0x4093dc - result::unwrap_failed::h14285438085691555396
   6:           0x405e97 - main::h990b2fd14e5def49jqe
   7:           0x448a90 - sys_common::unwind::try::h12227282963465111153
   8:           0x409df0 - main
   9:           0x4013b4 - _tmainCRTStartup
  10:           0x4014e7 - mainCRTStartup
  11:     0x7ffb9cb08101 - strncmp
```
which translates to `Invalid access to memory location`. Disabling LTO fixes the problem, but increases binary size and decreases performance.

**Comment by NeoLegends** [comment]
My testing has shown that [this](https://github.com/tomaka/glutin/blob/9a129aa86204cb798d33b3ed009de14e342748c1/src/api/wgl/mod.rs#L704) is where the error occurs. Now I'll have to figure out why.

**Comment by NeoLegends** [comment]
Just tested the example on another machine, it crashed again. So it indeed is an error within glutin / rustc / LLVM.

**Comment by tomaka** [comment]
There kinds of errors are usually very low-level. It will probably be hard to find the cause.

**Comment by Eroc33** [comment]
This error occurs for me on nightly-x86_64-pc-gnu-windows, but not nightly-i686-pc-gnu-windows, so maybe it's related to the size of some winapi structure in memory?

**Comment by tomaka** [comment]
Pinging @retep998 I guess

**Comment by retep998** [comment]
I'd just like to point out the third parameter to `CreateWindowExW` is an `LPCWSTR` and you're passing a pointer to a narrow string.

**Comment by mchesser** [comment]
Recently I started hitting this issue on regular release builds (`lto = false`). Removing the parameter (https://github.com/mchesser/glutin/blob/master/src/api/wgl/mod.rs#L705) as pointed out by @retep998 fixes the issue for me.

**Comment by sinesc** [comment]
Is this in 0.6.1 ? I seem to be running into the same issue with recent rust versions without using lto.

**Comment by retep998** [comment]
@sinesc 0.6.1 is older than the PR that fixed this, so no. You'd probably need 0.6.2 at a minimum.

**Comment by gyc990326** [comment]
I guess the GetLastError() 998 happen in CreateWindowExW because the cpu requires 2-byte align to read a wide char, so if the address does not aligned, such as 0x00012332421 whose the bit 0 is non-zero, the function will fail. I suggest that the linker has some bug in handling the align requirement. 
Debug information is required to comfirm my theory.

**Comment by kevinw** [comment]
If anyone needs another way to repro, I just hit this bug as well, running `cargo run --release --example opengl` after cloning the rust-openvr/rust-openvr project.
