### ISSUE TITLE
Support for High DPI on Windows

### ISSUE THREAD

**Issue by NeoLegends** [tomaka/glutin#757]
Currently, glutin doesn't support High DPI monitors on Windows. This is a pity for the people using newer convertibles that usually feature high resolution screens.

**Comment by tomaka** [comment]
Triage: not sure if this is an OpenGL problem or a winit problem.
What exactly is not supported?

**Comment by francesca64** [comment]
This is a winit problem and should be closed. tomaka/winit#469 tomaka/winit#62 tomaka/winit#332
