### ISSUE TITLE
Mouse grabbing restricts mouse movement events to window frame

### ISSUE THREAD

**Issue by ElArtista** [tomaka/glutin#764]
When entering in mouse grabbed mode one must be able to receive events infinitely on any direction.
Now after moving mouse in any direction after a while (i suppose the hidden cursor hits the window frame) we do not get any further mouse move events, making it impossible to create a first person camera with the library.

**Comment by tomaka** [comment]
The idea is that you're supposed to manually set the mouse position to the center of the window at each frame.

I think that's how you do it with other libraries as well.

**Comment by ElArtista** [comment]
That is an interesting idea. Although if i remember correctly glfw does not restrict mouse movement in grab mode. Still thanks for helping!

**Comment by est31** [comment]
What to do on wayland btw? Wayland does not provide a feature to set the mouse position. Instead, it offers pointer confinement.
