### ISSUE TITLE
Setting the window icon

### ISSUE THREAD

**Issue by est31** [tomaka/glutin#771]
From reading the API, I see no way of setting the window icon.

It would be novel to the crate as it would involve directly handling image data. What do you think: is this crate a good place for this, or should this be handled by an external crate that depends on glutin and glutin gives the window handle to that crate (as `get_xlib_window` does already for xlib)?

**Comment by tomaka** [comment]
There was some discussion in #688 already about that.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/69
