### ISSUE TITLE
Enable `Less` and `Greater` Keys on X11

### ISSUE THREAD

**Issue by indiv0** [tomaka/glutin#775]
Would it be possible to enable the [`Less`](https://github.com/tomaka/glutin/blob/master/src/api/x11/events.rs#L203) and [`Greater`](https://github.com/tomaka/glutin/blob/master/src/api/x11/events.rs#L205) keys on X11?
Is there any particular reason why they're not enabled?

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/71
