### ISSUE TITLE
impl Clone for WindowBuilder

### ISSUE THREAD

**Issue by jansegre** [tomaka/glutin#779]
Doing this would be useful for this my use case: I want a context `with_multisampling`, but it is not a hard requirement, so I simply end up trying `build_glium`, and if it `Err`s I have to set up a new `WindowBuilder` from scratch. It would be more ergonomic to set up my minimal required `WindowBuilder` and re use it (with `.clone()`).

What do you think about this?

**Comment by tomaka** [comment]
Should be easy to implement.

**Comment by LFalch** [comment]
Shouldn't this be closed now as of #780?
