### ISSUE TITLE
Software rendered context created on OS X 10.9

### ISSUE THREAD

**Issue by jminer** [tomaka/glutin#781]
I'm using OS X 10.9.5, and tried running the beginnings of a game on my MacBook Pro 2011 with a Radeon 6490M. Whereas it ran at over 400 FPS on my Windows desktop (Radeon 5770 from 2010), it only got roughly 0.25 FPS on my laptop (and the CPU was maxed out). Taking into account the smaller resolution, it was about 6,400 times slower, so I figured it was using software rendering, and I verified it was. Here is how I am creating the window:

```
let display = glutin::WindowBuilder::new()
              .with_dimensions(850, 480)
              .with_title(String::from("Test"))
              //.with_multisampling(4)
              //.with_vsync()
              .with_depth_buffer(24)
              .build_glium()
              .unwrap();
```

I tried with and without multisampling and vsync, and it didn't make any difference.

I tried changing glutin to pass `NSOpenGLPFAAccelerated` and `NSOpenGLPFANoRecovery`, but then it fails to create any context. However, I changed [the version check](https://github.com/tomaka/glutin/blob/master/src/api/cocoa/helpers.rs#L21) to request a 3.2 context on this computer, and then it successfully creates a hardware accelerated context. Can anyone else with 10.9 reproduce this? Should glutin request a 3.2 context on 10.9? It seems bad to create a software rendered context.

**Comment by kvark** [comment]
I see it, working on a fix now.
This is pretty severe as it makes any glutin-based app dead slow.
