### ISSUE TITLE
Certain keys report no VirtualKeyCode on Windows

### ISSUE THREAD

**Issue by Kasran** [tomaka/glutin#785]
I'm on a Windows 10 computer, using a USB keyboard (a Razer Blackwidow Chroma, if it matters). I've been playing around with glutin lately, using this bit of code in my event-poll match statement to look at what information is reported for key events:

``` rust
glium::glutin::Event::KeyboardInput(pr, sc, kc) => {
    let k = match kc {
        Some(c) => format!("{:?}", c),
        None => "unknown key".to_string()
    };
    println!("{:?}: key {} ({})", pr, sc, k);
}
```

So, when an event is received, I'll get a message like `Pressed: key 30 (A)` on the console.

The issue is that some keys don't seem to report a VirtualKeyCode - namely:
- the Windows key, scancode 91 on my keyboard
- the backtick/tilde key, scancode 41 (the one that's next to 1 and above Tab on some keyboards)
- the backslash `\` and forward slash `/` keys, scancodes 43 and 53 respectively
- either square bracket key, scancodes 26 and 27
- the semicolon `;` key, scancode 39
- the apostrophe `'` key, scancode 40

(The scancodes are all for my keyboard; I haven't tested them anywhere else and they may be completely different on different keyboards for all I know. I'm not sure what the number actually comes from.)

This behavior seems strange, because there are `VirtualKeyCode` enum options listed for at least some of those keys (I noticed `Apostrophe` and `Backslash` right away skimming through the list just now). What could be causing these omissions - is it something unimplemented in glutin, or some oddity with my operating system or keyboard?

**Comment by tomaka** [comment]
You can take a look here at how codes from Windows are translated into VirtualKeyCodes: https://github.com/tomaka/glutin/blob/master/src/api/win32/event.rs

**Comment by CryZe** [comment]
The '-' and the '+' key are treated at "Add" and "Subtract" on Linux, but not on Windows. On Windows only the Numpad Keys work.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/74
