### ISSUE TITLE
Window resizing arrows are missing on Win10

### ISSUE THREAD

**Issue by Radviger** [tomaka/glutin#799]
Resizable window, created by glutin missing resizing arrow icons.
![8fc33876-407b-11e6-8524-80f1501b641d](https://cloud.githubusercontent.com/assets/5886950/16545003/783d014c-413d-11e6-8794-88f4f1cfa6c7.gif)

**Comment by oahner** [comment]
I have the same behavior on Windows 7.

**Comment by ruabmbua** [comment]
I have the same behaviour on Windows 10 Redstone 1 & Windows 10 Threshold 2.
I also have to note, that resizing seems to be bugged in another way too. Most of the time it is very hard to grab the border for some reason. Maybe there is some kind of border thickness for grabbing, which is set to 1?

**Comment by novacrazy** [comment]
Any updates on this issue?

I'm experiencing the same thing on Windows 10.0.14393, and I'd rather not switch from Glutin to GLFW.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/76
