### ISSUE TITLE
Implement swap interval for x11

### ISSUE THREAD

**Issue by tomaka** [tomaka/glutin#80]

**Comment by andrewrk** [comment]
Here's how GLFW does it:

https://github.com/glfw/glfw/blob/4188c263e31ec3d5da99a77d939ab56bc199fda6/src/glx_context.c#L507

I'll take a stab at this.

**Comment by andrewrk** [comment]
eh I'm going to give up and go to glfw-rs for now. I'm not sure how to implement this given that it needs to  call functions loaded dynamically at runtime.

**Comment by andrewrk** [comment]
I don't think this is closed since you can't call swap_interval(0)

**Comment by tomaka** [comment]
I opened #228
