### ISSUE TITLE
Dropping Window doesn't close it (X11)

### ISSUE THREAD

**Issue by gmorenz** [tomaka/glutin#805]
For example, I would expect the following code to close the window immediately, instead of closing it when you kill the process

``` rust
extern crate glutin;

fn main() {
    glutin::Window::new();
    loop {}
}
```

Adding `(self.display.xlib.XSync)(self.display.display, 0);` to the end of [`XWindow::drop`](https://github.com/tomaka/glutin/blob/master/src/api/x11/window.rs#L102) fixes the issue, I'm not familiar enough with X to say if it's the right way to fix the issue.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/79
