### ISSUE TITLE
Add support for min/max dimensions on OSX

### ISSUE THREAD

**Issue by bvssvni** [tomaka/glutin#812]
Currently, this is not supported on OSX, see https://github.com/tomaka/glutin/blob/master/src/api/cocoa/mod.rs#L283-L284

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/80

**Comment by frewsxcv** [comment]
I have a winit branch with this implemented. Will open a PR soon.

**Comment by frewsxcv** [comment]
PR opened: https://github.com/tomaka/winit/pull/89.
