### ISSUE TITLE
Window creation fails on Arch Linux with nvidia drivers

### ISSUE THREAD

**Issue by pengowen123** [tomaka/glutin#821]
I installed the `nvidia` and `nvidia-libgl` packages on Arch Linux, and made a simple cargo project (glutin 0.6.2):

    extern crate glutin;

    fn main() {
        let window = glutin::WindowBuilder::new().build();
    }

When running it I get these errors:
`libGL error: No matching fbConfigs or visuals found`
`libGL error: failed to load driver: swrast`

If there is any additional info I should provide let me know.

**Comment by tomaka** [comment]
The errors you mention come from your driver and not from glutin.
Therefore my guess is that you have a bad installation.
