### ISSUE TITLE
OsError("CreateWindowEx function failed: Invalid access to memory location. (os error 998)")

### ISSUE THREAD

**Issue by dten** [tomaka/glutin#833]
`OsError("CreateWindowEx function failed: Invalid access to memory location. (os error 998)")`

I'm getting this error but only with --release (also it used to work fine)
```
let b = glutin::WindowBuilder::new();
let display = b.build_glium()
               .expect("build_glium err");
```
edit:
have found it has an error when using stable-x86_64-pc-windows-gnu but works fine when using stable-i686-pc-windows-gnu

this is using glium 0.15

have done some invetigating with rustup and looks like something changed in 1.13

nightly-2016-11-21-x86_64-pc-windows-gnu ❌ 
1.13.0-x86_64-pc-windows-gnu ❌ 
1.13.0-x86_64-pc-windows-msvc ❌ 
1.13.0-i686-pc-windows-gnu ✔️  
1.12.1-x86_64-pc-windows-gnu ✔️ 
1.12.0-x86_64-pc-windows-gnu ✔️

**Comment by CryZe** [comment]
Oh yeah, I recently had that too. I thought it was just an old version of glutin, so I updated it and everything worked again. But it seems it's a regression in Rust.

**Comment by dten** [comment]
Trying to narrow it down a bit more :) have found glutin `0.6.1` which glium `0.15` uses is bad but `0.6.2` is fine. Still Rust though!

**Comment by CryZe** [comment]
Could be related to drop flags being gone in 1.13.

David Hewson <notifications@github.com> schrieb am Sa. 26. Nov. 2016 um
23:20:

**Comment by dten** [comment]
the related commit between 0.6.1 and 0.6.2 is probably this https://github.com/tomaka/glutin/commit/1aeb48a0062fa6c4cf3f43f94335da4fa2144c48

**Comment by dten** [comment]
so this just https://github.com/tomaka/glutin/issues/756 so from a glutin point of view it's fixed. For Rust it looks lucky that it ever worked really and I'm not sure how much to count it as a regression

**Comment by tomaka** [comment]
Running `cargo update` will update your project to glutin 0.6.2
I don't think it's useful to release glium 0.15.1, as people would have to run `cargo update` anyway to update glium.

**Comment by dten** [comment]
Didn't realise in the dependencies "0.6.1" is the same as "^0.6.2" and `cargo update` has pulled in 0.6.2
I'm sure I tried that though :/
