### ISSUE TITLE
Pen/Tablet Input Support

### ISSUE THREAD

**Issue by cjhowe** [tomaka/glutin#836]
I propose we support pen tablet input, such as on devices like the Surface Pro/Studio, Galaxy Note, and eventually the Apple Pencil. These devices support things like pressure sensitivity and rotation/gyro. I don't think this is necessarily relevant to games (although it definitely can be), but it's definitely relevant to the larger digital 3D community.

**Comment by tomaka** [comment]
Please open an issue to winit instead: https://github.com/tomaka/winit
