### ISSUE TITLE
Unable to Create Andoid Native Shared Library: 'cannot locate symbol "cargo_apk_injected_glue_get_native_window"'

### ISSUE THREAD

**Issue by chrisliebert** [tomaka/glutin#838]
README.md states "To compile the examples for android, initialize the submodules, go to deps/apk-builder/apk-builder and run cargo". There does not appear to be an apk-builder or "deps"; are these instructions still valid?

Although android_glue is a great framework, I do not want to use it's generated Android app configuration, and I already have a Gradle build script which invokes cargo to create a native JNI shared library in Rust and bundle it in the .apk, but when I try to load shared library from an Android Activity with:
```	
static {
		try {
			System.loadLibrary("quick3dwrapper");
		} catch (UnsatisfiedLinkError e) {
			e.printStackTrace();
			System.exit(1);
		}
}
```
, I see the following exception:

```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "cargo_apk_injected_glue_get_native_window" referenced by "libquick3dwrapper.so"...
```

It seems Glutin applications for Android require the cargo_apk_injected_glue package that can be generated using `cargo-apk` instead of `cargo build --target=arm-linux-androideabi`, so I tried adding the following to lib.rs but it had no effect:

```
#[cfg(target_os = "android")]
#[link(name = "cargo_apk_injected_glue")]
fn some_function() {...}
```

In fact, building with `cargo-apk` or `cargo build --target=arm-linux-androideabi` seem to produce identical results. I have also tried adding the following to Cargo.toml, however it does not appear to solve the issue either:
```
[target.arm-linux-androideabi.dependencies]
cargo-apk = "0.1.7"
```

This is how I included Glium in Cargo.toml:
```
[dependencies]
glium = "*"
```

I would really like to see Glutin running from a Rust JNI library, any advice will be greatly appreciated.

**Comment by tomaka** [comment]
Glutin needs a way to obtain the handle to the ANativeWindow, which can only be known by the function called by Android at initialization.
If you use your own system, you will need some way to provide that in some way.

**Comment by chrisliebert** [comment]
Thanks, @tomaka. I was able to resolve the error by linking to a separate project with crate-type=`staticlib` from the lib.rs and ffi.rs generated by cargo-apk. The JNI wrapper shared library is linked to the glue static lib and now I can call some Rust code from the Java Activity however it will receive SIGABT if there is no main-loop. I also recieve SIGABT -6 when attempting to create a boxed GlutinFacade through an extern "C" rust method. It could be a matter of configuring EGL and/or GLSurfaceView on the Java side, I will post a full solution if I get it working.

**Comment by ZeGentzy** [comment]
Please reopen if you are still working on this.

**Comment by lattice0** [comment]
I want to render to a SurfaceTexture on Android, thus I don't use any of the windowing stuff. I'm using glium which uses glutin, so I get this same error. How should I proceed in this case?
