### ISSUE TITLE
Integrate with `winit`

### ISSUE THREAD

**Issue by kvark** [tomaka/glutin#839]
I want the following chain of conversions to be accessible:
`winit::WindowBuilder` -> `glutin::WindowBuilder` -> `glutin::Window` -> `winit::Window`

The first link is needed for the window constructors to have a unified interface: getting `winit::WindowBuilder` on the input and working from it.

The last link is needed for the window-agnostic frameworks/apps, which just get `winit::Window` and from it use the events as well as `swap_buffers`.

This is a blocker for https://github.com/gfx-rs/gfx/issues/907
cc @ozkriff

**Comment by Plasticcaz** [comment]
I'm looking for something to do, maybe I'll have a go at this.

**Comment by kvark** [comment]
@Plasticcaz thanks for taking a bite at it!
If the work is non trivial, and you'd like to get the feedback sooner rather than later, then please by all means submit a PR with [WIP] before the name.

**Comment by Plasticcaz** [comment]
Thanks... 

Looking at src/platform and src/api/android, it's obvious to me how I could easily expose winit_window from a window in Windows, Android, and MacOS, but I'm not sure with the other platforms... 

Linux appears to not keep the winit window... It looks like it takes what it needs, and then throws it out.

**Comment by francesca64** [comment]
Is this still an issue?

**Comment by kvark** [comment]
I believe we are happy now :)
