### ISSUE TITLE
Add serialization of enums via Serde

### ISSUE THREAD

**Issue by kingoflolz** [tomaka/glutin#842]
I am using glutin in a game and it would be useful if the crate provided serialization and deserialization of all the enums using an optional dependency to Serde.

Is this something the maintainers are looking into doing? If not, I will be happy to do it myself.

**Comment by tomaka** [comment]
Sorry but I don't want to depend on any library not directly related to windowing/OpenGL.

**Comment by the-kenny** [comment]
Keep in mind that you can easily wrap the enums of glium in a tuple struct,
then implement from+into and serde's traits on them.

Am 27.12.2016 13:35 schrieb "tomaka" <notifications@github.com>:

**Comment by Xaeroxe** [comment]
@tomaka Amethyst has need of this feature as well.  The dependency would be 100% optional and would make things like input rebinding menus much easier to make.  Are you still opposed to adding this?

**Comment by tomaka** [comment]
Yes.
However would it help to have methods on `VirtualKeyCode` to convert back and forth with &'static str?

**Comment by Xaeroxe** [comment]
@tomaka Yeah that would certainly help.  It's not quite as high priority for Amethyst as it was when I made that comment (an hour ago) because I figured out how to get remote derive working with this.  However if you add those functions it'd probably cut down on boilerplate for us.
