### ISSUE TITLE
Sample code for shared contexts

### ISSUE THREAD

**Issue by jasongrlicky** [tomaka/glutin#852]
Hey there! I'm trying to implement an app where I share contexts between multiple headless renderers. It seems like it should be possible to do this using glutin via [`GLAttributes`](https://docs.rs/glutin/0.7.3/glutin/struct.GlAttributes.html), but when I attempt to use it as I've shown below, I get a compilation error:

```rust
extern crate gl;
extern crate glutin;

fn main() {
    let c1 = glutin::HeadlessRendererBuilder::new(640, 480).build().unwrap();
    unsafe { c1.make_current() }.unwrap();
    gl::load_with(|symbol| c1.get_proc_address(symbol) as *const _);

    let mut builder = glutin::HeadlessRendererBuilder::new(640, 480);
    let mut attributes = glutin::GlAttributes::default();
    attributes.sharing = Some(&c1);
    builder.opengl = attributes; 
    let c2 = builder.build().unwrap();
    unsafe { c2.make_current() }.unwrap();
    gl::load_with(|symbol| c2.get_proc_address(symbol) as *const _);
}
```
The error I'm seeing is:

```
error[E0308]: mismatched types
  --> examples/sharing.rs:15:22
   |
15 |     builder.opengl = attributes;
   |                      ^^^^^^^^^^ expected struct `glutin::platform::platform::headless::HeadlessContext`, found struct `glutin::HeadlessContext`
   |
   = note: expected type `glutin::GlAttributes<&glutin::platform::platform::headless::HeadlessContext>`
   = note:    found type `glutin::GlAttributes<&glutin::HeadlessContext>`
```

After looking into it, I found `glutin::HeadlessContext`'s `.context` property, which I believe is of the right type, but doesn't seem to be public. Can anyone point me in the right direction for setting up shared contexts? Once we get it sorted out, I'll gladly contribute back a new example that demonstrates it. Thank you!

**Comment by tomaka** [comment]
This is clearly a problem here: https://github.com/tomaka/glutin/blob/06247af952aa29c0eb5fecf89fd099004e4bc2a0/src/headless.rs#L21
It should be `HeadlessContext` and not `platform::HeadlessContext`.

**Comment by jasongrlicky** [comment]
Oh, great! Thank you so much for the quick response. I was going to try and fix it and submit a patch, but I ran into https://github.com/tomaka/glutin/issues/853 when trying to build Glutin locally, and am not an experienced-enough Rust developer to work around that one.

**Comment by jasongrlicky** [comment]
Thanks so much for fixing #853, @tomaka 👍  Now that I've had a chance to dive into the code, I realized that context sharing isn't itself supported on Cocoa yet (#135). I'm definitely too new of a Rust developer to tackle that whole feature, but maybe someday.
