### ISSUE TITLE
Error "`CoreFoundation.framework` is being linked by more than one version of the package

### ISSUE THREAD

**Issue by bvssvni** [tomaka/glutin#853]
glutin "0.7.3".

```
$ cargo build
error: native library `CoreFoundation.framework` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once

  core-foundation-sys v0.2.3
  core-foundation-sys v0.3.0
```

**Comment by bvssvni** [comment]
I wrote up a workaround here https://github.com/PistonDevelopers/piston/issues/1152

**Comment by tomaka** [comment]
As usual I don't have a Mac and I have no clue how this whole core-foundation/obj/etc. stuff works, so I can't really fix this.

**Comment by Bogidon** [comment]
There are two problems going on here,

1) `core-foundation = "0"` fetches the most current version: `0.3.0`

**Solution**:
Change `Cargo.toml:32`:
```diff
- core-foundation = "0"
+ core-foundation = "0.2.3"
```
Run `cargo update`

2) Cargo seems to have a tough time resolving dependencies:
[`winit 0.5.9`](https://crates.io/crates/winit/0.5.9)`: core-foundation = "^0"`
[`core-graphics (0.2-0.5)`](https://crates.io/crates/core-graphics/0.5.0)`: core-foundation = "^0.2"`

In my opinion cargo should strive to fit nested dependencies within all parents if possible. In this case, 0.2.3 would do the trick but cargo chooses 0.3.0 for winit and 0.2.3 for core-graphics.

**Workaround**:
Change `Cargo.lock:485`:
```diff
- "core-foundation 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)",
+ "core-foundation 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)",
```


@tomaka I'm new to rust world, but what's the reason for `Cargo.lock` being in the `.gitignore`? If it weren't we could fix this for everyone, but as is they'll have to apply patch 2) manually.
