### ISSUE TITLE
poll_events()/wait_events() are not enough for power efficient GUI apps

### ISSUE THREAD

**Issue by pedrocr** [tomaka/glutin#855]
The current events API is not enough to be able to have a GUI app that can both sit idle for minutes/hours when there are no new events as well as reacts to outside events not from the GUI. With the two current APIs you can:

  * **poll_events()**: Run a 60fps loop by first polling for events, then checking for outside events, then sleeping for 16ms. This gives you the correct behavior but has 60 wakeups per second which costs a bit of power.
  * **wait_events()**: Since it blocks the power issue is solved but there is then no way to react to other events. 

The ideal API would be a form of wait_events() with a way to inject an artificial event from another thread so that it can be unblocked on demand. Maybe there's already a way of doing this?

**Comment by pedrocr** [comment]
Btw I came across this limitation while working on a conrod app event loop:

https://github.com/PistonDevelopers/conrod/pull/915

**Comment by jwilm** [comment]
@pedrocr You can get a `WindowProxy` which has a `wakeup_event_loop()` method. Looks like event iterators are going [go away soon](https://github.com/tomaka/winit/pull/126) anyway.

**Comment by pedrocr** [comment]
@jwilm thanks, this does indeed work fine and makes for very simple code.
