### ISSUE TITLE
Support for ANGLE on Windows

### ISSUE THREAD

**Issue by siriux** [tomaka/glutin#860]
I'm not a windows developer, but I'm writing a cross platform app that has to work on windows, and I cannot rely on anything but OpenGL 1.1 without extra drivers (not under my control).

I've seen that there is project called ANGLE that solves this problem by translating OpenGL ES calls into DirectX, and apparently it works quite well (it's used by chrome and firefox). This solves the need for extra drivers, as DirectX is supported by default.

Do you think it could be supported in glutin?

The Google repo of the library is: https://github.com/google/angle
The Microsoft repo is: https://github.com/google/angle
And binaries can be downloaded from: https://www.nuget.org/packages/ANGLE.WindowsStore

**Comment by viftodi** [comment]
This is not an issue at all mate.

Most Windows PC will definitely have > OpenGL 1.1 support.

Even the integrated intel GPUs support like Openg 4.x on the latest versions.

Also Angle is mainly meant to bring opengl ES support for the browser and still requires proper drivers and modern opengl versions.

I don't know what your requirements are, but I am pretty sure you're misguided, you don't need extra drivers just the gpu drivers (Without GPU drivers you wouldn't even get proper 3D acceleration on windows anyway)

This issue should be closed.

**Comment by siriux** [comment]
Thanks, I'll close it. 

I guess it's safe to assume that on windows the gpu driver is always installed on "modern" systems.

**Comment by SimonSapin** [comment]
For future archeologists: indeed ANGLE is typically not needed, Glutin will typically be able to create a GL context *somehow* on many systems.

However if for some reason (CC https://github.com/servo/webrender/pull/2458) there is a need to use ANGLE specifically, I’ve packaged it into a crate at https://crates.io/crates/mozangle, and https://github.com/tomaka/glutin/pull/998 should allow using it with Glutin. Alternatively, it should be possible to create a bare winit window, use [`WindowExt::get_hwnd`](https://docs.rs/winit/0.11.2/x86_64-pc-windows-msvc/winit/os/windows/trait.WindowExt.html#tymethod.get_hwnd), and then use ANGLE’s EGL functions directly, similar to [`platform/windows/context.rs`](https://github.com/tomaka/glutin/blob/master/src/platform/windows/context.rs) and [`api/egl/mod.rs`](https://github.com/tomaka/glutin/blob/master/src/api/egl/mod.rs).

**Comment by SeleDreams** [comment]
A more useful application of ANGLE in current days is the ability to run opengl programs in directx or metal which can be good for cross platform programs. like if they run on macos or if they run on xbox
