### ISSUE TITLE
Update cgl to v0.2 and winit to v0.6

### ISSUE THREAD

**Issue by sotaroikeda** [tomaka/glutin#863]
It is necessary for servo/webrender#771.

**Comment by sotaroikeda** [comment]
Updating seems to be affected by tomaka/winit#132 change. It request code update of glutin.

**Comment by tomaka** [comment]
Yes, cc-ing https://github.com/tomaka/winit/issues/124

If it's a change required for servo, you should probably modify servo's fork of glutin. Their fork is something like six months late and doesn't depend on winit yet.

**Comment by sotaroikeda** [comment]
Thanks for info!

**Comment by sotaroikeda** [comment]
tomaka/glutin#864 is going to update winit to v0.6
