### ISSUE TITLE
NoX11Connection when compiling for i686 linux

### ISSUE THREAD

**Issue by erethedaybreak** [tomaka/glutin#869]
I'm working on something for 32bit arch, and so I am compiling with `nightly-i686-unknown-linux-gnu`.

It works with the `x86_64` toolchain, but with the `i686` toolchain somehow the X11 connection is not available. I realise the connection is made in winit, but I thought I'd file it here.

This can be reproduced with the window example:

```
rustup default nightly-i686-unknown-linux-gnu
cargo run --example window
...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoBackendAvailable(NoX11Connection)', /checkout/src/libcore/result.rs:860
```

**Comment by DmitryHetman** [comment]
Use wayland compositor instead of X11.

**Comment by erethedaybreak** [comment]
Yes, that would avoid this.

The X11 specific thing should be fixable though. Later on I followed the Khronos GLX example to write a small thing to open a GLX window, and that worked.

Unfortunately it didn't give me any ideas for where this bug is coming from, I completely got lost in glutin's numerous modules and dispatch layers.

**Comment by francesca64** [comment]
This should be reported to [winit](https://github.com/tomaka/winit) instead, and if you're lucky, was already fixed.
