### ISSUE TITLE
Maximized window on startup?

### ISSUE THREAD

**Issue by fschutt** [tomaka/glutin#871]
Hi. I wanted to ask if it is possible to get a maximized window on startup? As far as I can see, this isn't currently possible. I could possibly get the window dimensions of the screen and the use these as the dimensions for the window. However, this doesn't actually maximize the window.

Implementing this would be quite a bit of work - the easiest reference for this would be the SDL library. Its source contains the implementations of window maximizing for Windows, WinRT, X11, MIR, Coacoa and others (the specific functions can be found in "/src/video/[platform]/SDL_[platform]window.c" ).

It would be a rather nice feature for the library because usually, when making desktop applications, you do want them to start in a windowed, but maximized (not fullscreen).

**Comment by ashkitten** [comment]
I believe this is implemented, can this issue be closed?
