### ISSUE TITLE
Add option to force GLES

### ISSUE THREAD

**Issue by computermouth** [tomaka/glutin#872]
On armhf Linux [at least on Debian/Ubuntu] software GL rendering libraries are a requirement of modern desktop environments to ensure that GL-based desktop applications have a backend.

Running a triangle example and printing out the Api enum returns OpenGl on a board with GLES drivers. I'm jumping to the conclusion that GL is probed first or preferred to GLES. It'd be great to be able to specify that my Glutin prefer GLES on armhf Linux.

**Comment by sjaustirni** [comment]
I haven't tried it, but you should be able to implement it with [GlRequest::Specific](https://tomaka.github.io/glutin/glutin/enum.GlRequest.html#variant.Specific) and [WindowBuilder::build_strict()](https://tomaka.github.io/glutin/glutin/struct.WindowBuilder.html#method.build_strict).

**Comment by ZeGentzy** [comment]
As mentioned above, you should be able to do it with `GlRequest`, see https://docs.rs/glutin/0.19.0/glutin/enum.GlRequest.html

Closing. Re-open if this is still an issue.
