### ISSUE TITLE
Locking window size or disabling resizing

### ISSUE THREAD

**Issue by evrimoztamur** [tomaka/glutin#877]
I've been looking at past commits and it seems like #681 and #683 were never fully implemented. Seeing there is no progress on either one of these commits for over a year, I was wondering if any help is needed on this end.

Disabling resizing is a feature I need while using glium/glutin, so I'd appreciate it if anybody could direct me to the necessary changes required for this. The addition of a `resizable` flag to `glutin::WindowAttributes` would be very useful.

**Comment by TakWolf** [comment]
I have the same problem. What is the progress?
glutin‘s everything is great, except for this resizable flag.
So I had to use sdl to overdo it.

Whether there is a completed plan, or what is the current difficulty?

**Comment by Dooskington** [comment]
Having the same issue - would really love a resizable flag. 

I tried to set the min and max dimensions to be the same, but it doesn't work as expected. It disables resizing, but gives the wrong dimensions on Windows (but works on macOS). Basically, I am having the problem described in issue #681 which was apparently fixed.

**Comment by francesca64** [comment]
This is an issue with winit and should be closed. Relevant: tomaka/winit#65 tomaka/winit#127
