### ISSUE TITLE
Keyboard events (key and character input) are OS dependent

### ISSUE THREAD

**Issue by codec-abc** [tomaka/glutin#878]
Hi,

While working on Servo we discovered that the events related to the keyboard and thus characters don't come in the same order depending on the underlying OS.
To put it simply if I press the key 'a' in Windows I will get those events in the following order :

1. KeyboardInput event (down)
2. ReceivedCharacter 'a'
3. KeyboardInput event (up)

While on Linux (and probably Mac OS) it would be:

1. ReceivedCharacter 'a'
2. KeyboardInput event (down)
3. KeyboardInput event (up)

I tested SDL2 and GLFW and both use the fist "scheme" no matter if they are running on Windows or Linux.

**Comment by jwilm** [comment]
This can be closed
