### ISSUE TITLE
Can't initialize with an existing winit::EventsLoop

### ISSUE THREAD

**Issue by ebkalderon** [tomaka/glutin#880]
It would be nice to be able to initialize glutin with a `winit::EventsLoop` and not just `glutin::EventsLoop`. If I am working with multiple winit-based graphics backends alongside glutin, it's annoying not being able to pass in the vanilla `winit::EventsLoop` into `glutin::WindowBuilder::build()`.

Perhaps we could add a `glutin::EventsLoop::from_winit_events_loop()` method just like the existing `glutin::WindowBuilder::from_winit_builder()`?

**Comment by torkleyy** [comment]
Just took a look at it and it is really confusing how many `EventsLoop`s there are. Why are there platform wrappers in `glutin`? Isn't it possible to let `winit` do that?

**Comment by mitchmindtree** [comment]
@torkleyy winit handles platform-specific window stuff, while glutin handles platform-specific OpenGL stuff.

**Comment by ebkalderon** [comment]
@mitchmindtree If that's the case, would you mind explaining what platform-specific OpenGL stuff resides in `glutin::EventsLoop`? Looking at the code, I can't seem to find any.

**Comment by mitchmindtree** [comment]
`glutin::EventsLoop` is just a wrapper around `glutin::platform::EventsLoop` - the actual platform that is used [depends on which `cfg` is satisfied](https://github.com/tomaka/glutin/blob/master/src/platform/mod.rs#L3-L20) at compile time.

As for the platform `EventsLoop`s themselves, [here's the macOS specific GL context](https://github.com/tomaka/glutin/blob/master/src/platform/macos/mod.rs#L60), [here's the wayland one](https://github.com/tomaka/glutin/blob/master/src/platform/linux/wayland.rs#L15), [the x11 one](https://github.com/tomaka/glutin/blob/master/src/platform/linux/x11.rs#L47), etc.

The reason the distinction exists is to allow for the window-specific stuff (winit) to be used with non-GL graphics contexts (like Vulkan).

**Comment by mitchmindtree** [comment]
All that said, I agree with OPs suggestion that it would be nice if we had a method for building a `glutin::EventsLoop` from a `winit::EventsLoop`.

**Comment by ebkalderon** [comment]
@mitchmindtree Thanks for the detailed explanation! Indeed, I think it would be nice to be able to initialize from a `winit::EventsLoop`. If no one is willing to work on it, would you mind if I made a PR?

**Comment by kvark** [comment]
Given that `EventsLoop` is just re-exported currently from `winit`, I think this issue can be closed.

**Comment by francesca64** [comment]
I believe this can be closed, as AFAIK `glutin::EventsLoop` and `winit::EventsLoop` are literally the same type.

**Comment by ebkalderon** [comment]
Sounds good, thank you. Closing.
