### ISSUE TITLE
`decorated` and `resizable` do not work in Debian/Gnome shell/wayland

### ISSUE THREAD

**Issue by Boiethios** [tomaka/glutin#889]
```
$ uname -a
Linux *** 4.8.0-2-amd64 #1 SMP Debian 4.8.11-1 (2016-12-02) x86_64 GNU/Linux
```

with `GNOME 3.22.2` using `wayland`.

I tried the example:

```
extern crate piston_window;

use piston_window::*;

fn main() {
    let mut window: PistonWindow =
        WindowSettings::new("Hello Piston!", [640, 480])
		.exit_on_esc(true).decorated(true).resizable(true).build().unwrap();
    while let Some(e) = window.next() {
        window.draw_2d(&e, |c, g| {
            clear([1.0; 4], g);
            rectangle([1.0, 0.0, 0.0, 1.0], // red
                      [0.0, 0.0, 100.0, 100.0],
                      c.transform, g);
        });
    }
}
```

I also tried the frontpage glutin example: there were no window.

My window is not decorated, and I cannot resize it.

I tried in a gnome session using X11, and there were no issue: the window was decorated and resizable.

There is no problem with the `SDL2` backend.

(This is a c/c from an issue I opened in a wrong place: [https://github.com/PistonDevelopers/piston/issues/1157](url))

**Comment by vberger** [comment]
Looks like a duplicate of https://github.com/tomaka/winit/issues/163

**Comment by Boiethios** [comment]
Sorry. This is difficult in this kind of big projects to find the right place to report a bug.
