### ISSUE TITLE
X11 doesn't like creating and destroying a lot of windows

### ISSUE THREAD

**Issue by tomaka** [tomaka/glutin#89]
To reproduce, clone https://github.com/tomaka/glium/ and run `cargo test`.

I don't know if it's some kind of race-condition, or just events not being processed correctly.

**Comment by cmr** [comment]
@tomaka I'm curious how piglit gets past this. Or maybe they use separate processes. Worth looking into.

**Comment by tomaka** [comment]
I think they just use a single thread (this is python after all).
If I run glium's tests with `RUST_TEST_THREADS=1`, everything works fine.

**Comment by cmr** [comment]
That seems plausible.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/32
