### ISSUE TITLE
ModifiersState not exposed

### ISSUE THREAD

**Issue by eugeneyche** [tomaka/glutin#895]
Preface by saying I am new to Rust so this might not be a valid issue.
`WindowEvent::KeyboardInput` uses `winit::ModifiersState`, but glutin does not `pub use` it.

**Comment by eugeneyche** [comment]
I have a commit ready, but I'm new to contributing; how do I push a branch to start a pull request?

**Comment by Valloric** [comment]
@eugeneyche The usual way to create a pull request on GitHub is by pushing a commit to a new upstream branch on your own clone of the repo. Then got to the webpage of your repo and you'll see a banner at the top asking you would you like to create a pull request on the original repo.

**Comment by eugeneyche** [comment]
Thanks! Ref'ing pull rq #896
