### ISSUE TITLE
Move glutin to the new glium organisation?

### ISSUE THREAD

**Issue by mitchmindtree** [tomaka/glutin#898]
Recently, glium was moved to [its own organisation](https://github.com/glium) in order to make it more obvious that glium is now moreso maintained by the community around it as @tomaka (the original maintainer) will be busy with other projects for the foreseeable future. See the discussion [here](https://github.com/glium/glium/issues/532).

I think it would be worth moving glutin to the glium organisation for the same reasons - to indicate that glutin is now moreso maintained by the community than by tomaka.

I think the glium organisation is suitable as their histories are intertwined, they were founded by the same author and although neither *require* the other, they were originally designed to work as building blocks towards a common purpose.

To be clear, I don't mean to suggest that glium requires/prioritises glutin or vice versa (e.g. I believe gfx use glutin without glium and some sdl2 users use glium without glutin), just that glium is probably the most reasonable community organisation that currently exists that could host glutin for community development. Similarly to how [webrender is maintained under the servo organisation](https://github.com/servo/webrender), despite not being exclusively useful to servo (e.g. [this user is attempting to use it for game UI](https://github.com/Thinkofname/stylish)).

## Alternative

Another organisation could be created specifically for glutin. However, this might require more work on behalf of tomaka in terms of setup, and more work for maintainers to keep track of both organisations.

**Comment by kvark** [comment]
I think it's a good move to take some load off @tomaka as they are no longer focused on GL. Moving `glutin` into the same group as `glium` doesn't sound too bad, as long as:
  - the group it self is not called `glium`, since this signifies heavy affiliation
  - `winit` is left out of the group

**Comment by ZeGentzy** [comment]
Closing in favor of discussion over at winit.
