### ISSUE TITLE
Upgrade winit version?

### ISSUE THREAD

**Issue by expenses** [tomaka/glutin#902]
Currently, glutin fails to build on OS X nightly because it depends on an older version of cocoa, [which is currently broken on nightly](https://github.com/tomaka/winit/commit/886eab5c7ee26cb2535b7a46050a628411561ae9). Glutin depends on both [cocoa 0.3.2](https://github.com/tomaka/glutin/blob/master/Cargo.toml#L31) and [winit 0.6.3](https://github.com/tomaka/glutin/blob/master/Cargo.toml#L17), which depends on the outdated cocoa version.

Upgrading the cocoa dependency works without problems, but upgrading winit is an issue because [`winit::EventsLoop` no longer has this `interrupt` function](https://github.com/tomaka/glutin/blob/master/src/platform/macos/mod.rs#L135).

**Comment by LPGhatguy** [comment]
There are a couple outstanding pull requests that address this in a couple of different ways.

There's potential for a redesigned API to reduce dependency on winit (#901) as well as a more conservative one for just upgrading and dealing with the minor breakages. (#900).

**Comment by mitchmindtree** [comment]
@expenses there are 3 PRs open right now to address this - see #897, #900 and #901. Feel free to use one of those branches in the meantime and/or leave a comment or some feedback on those PRs depending on what direction you'd like to see glutin go in!

**Comment by mitchmindtree** [comment]
@LPGhatguy you beat me to it :)
