### ISSUE TITLE
get_inner_size(_points) returns pixel size on several platforms

### ISSUE THREAD

**Issue by evolarium** [tomaka/glutin#903]
On Linux, Windows, and Android the winit get_inner_size calls return pixel values.  This results in window sizes larger than the actual pixel size being returned when get_inner_size_pixels is called and a hidpi factor is applied.

[Android Docs](https://developer.android.com/ndk/reference/group___native_activity.html#ga186f0040c5cb405a63d93889bb9a4ff1)

[Windows Docs](https://msdn.microsoft.com/en-us/library/windows/desktop/ff684173(v=vs.85).aspx)

I've tested the attached Linux patch, which fixes the issue for me.  This is the gfx triangle example before the patch:

![default](https://user-images.githubusercontent.com/5010373/27988682-0dece2d2-63e5-11e7-9244-2c05148d1d60.png)

After patch:

![patched](https://user-images.githubusercontent.com/5010373/27988681-0deb2a3c-63e5-11e7-9a84-18efaaf8f20d.png)

The change I applied:

[linux_hidpi_patch.txt](https://github.com/tomaka/glutin/files/1133272/linux_hidpi_patch.txt)

**Comment by umurgdk** [comment]
@evolarium I think those things are handled in winit now

**Comment by LPGhatguy** [comment]
@tomaka That pull request doesn't address this issue for Windows, which was one of the affected platforms.
