### ISSUE TITLE
`with_***_dimensions` uses wrong size

### ISSUE THREAD

**Issue by lukors** [tomaka/glutin#912]
On Windows 10

I'm using glutin in Conrod, but I think this is a glutin issue rather than a Conrod one, so I'm making an issue here for now.

When creating a window like this:
```rust
glutin::WindowBuilder::new()
        .with_dimensions(200, 200)
        .with_min_dimensions(200, 200);
```
The window is created with the expected size of 200x200. However, when I resize the window with my mouse cursor I can make it smaller than 200x200, but it still seems to limit the size at a point.

`with_max_size` seems to use a similarly wrong value for the size.

**Comment by LPGhatguy** [comment]
I think this is an issue with winit that glutin inherits: tomaka/winit#196

**Comment by lukors** [comment]
Ah yeah, that's it for sure. Closing this issue, thanks!
