### ISSUE TITLE
Distinguish stylus from finger touch (e.g. by radius)

### ISSUE THREAD

**Issue by marcianx** [tomaka/glutin#916]
The Touch event does not include a touch radius or any other obvious way to distinguish finger and stylus touch events. This is particularly useful for palm rejection on large screens when using a stylus. Could such support be added?

**Comment by marcianx** [comment]
Also, desktop and emscripten would be nice in addition to Android.

**Comment by francesca64** [comment]
This should be reported to [winit](https://github.com/tomaka/winit) instead.
