### ISSUE TITLE
Some keys are not recognized

### ISSUE THREAD

**Issue by Boscop** [tomaka/glutin#924]
Usually the keypress event looks like `KeyboardInput(state, scan_code, Some(key))`.
But when I press the following keys, I get `None` for `key` and only get the `scan_code`:
```
accent grave/tilde 41
lbracket 26
rbracket 27
backslash 43
semicolon 39
single quote 40
slash 53
win left 91
win right 92
```

Why am I getting None for `key` instead of the correct `VirtualKeyCode`?

OS: Win 8.1; Keyboard: Corsair K95 RGB Mechanical Cherry MX Brown, Layout: US

I usually work around this by doing something like this, but I'd prefer if glutin gives me the correct `VirtualKeyCode`:
```rust
match event {
	Event::KeyboardInput(state, scan_code, maybe_key) => {
		let key = match maybe_key {
			None => match scan_code {
				0x28 => VirtualKeyCode::Apostrophe,
				0x2B => VirtualKeyCode::Backslash,
				0x29 => VirtualKeyCode::Grave,
				0x1A => VirtualKeyCode::LBracket,
				0x1B => VirtualKeyCode::RBracket,
				0x5B => VirtualKeyCode::LWin,
				0x5C => VirtualKeyCode::RWin,
				0x27 => VirtualKeyCode::Semicolon,
				0x35 => VirtualKeyCode::Slash,
				_ => panic!(format!("0x{:02X}", scan_code))
			},
			Some(key) => key,
		};
...
```

**Comment by rukai** [comment]
https://github.com/tomaka/winit/commit/63fdc3f903954cd6771bd3e8df739e114d96ef90
This landed in winit last week.
Now you need to wait for:
1.  A new version of winit to be published.
2.  Glutin to start using the new version of winit.

**Comment by Boscop** [comment]
Thanks, it works!
I don't necessarily need `LWin` and `RWin`, but maybe someone else needs them..

**Comment by rminderhoud** [comment]
Looks like winit and glutin were updated, this can be closed?
