### ISSUE TITLE
Cannot disable vysnc.

### ISSUE THREAD

**Issue by thelearnerofcode** [tomaka/glutin#926]
```rust
let context = glutin::ContextBuilder::new() .with_vsync(false);
```
does not disable vsync as expected.
It seems to stall during the line:
```rust
self.window.swap_buffers().unwrap();
```
On gnome/wayland, if that makes a difference.

EDIT: tried with x-server instead of wayland, problem still continues.

**Comment by jansol** [comment]
Make sure your driver or compositor settings don't force vsync on.

**Comment by thelearnerofcode** [comment]
Thank you!

**Comment by LukasKalbertodt** [comment]
For future visitors, this might be useful: try executing your application with `vblank_mode=0`. It worked for me on Ubuntu 18.04.

```
$ vblank_mode=0 cargo run
```
