### ISSUE TITLE
Switching to non-fullscreen doesn't work on Windows 8.1

### ISSUE THREAD

**Issue by Boscop** [tomaka/glutin#929]
I want to use this function to switch between monitors and fullscreen/windowed at runtime.
```rust
fn window_context_builders<'a>(cur_monitor: usize, fullscreen: bool) -> (glutin::WindowBuilder, glutin::ContextBuilder<'a>) {
	let mut monitors = glutin::get_available_monitors().collect::<Vec<_>>();
	let i = cur_monitor % monitors.len();
	let monitor = monitors.remove(i);
	let window = glutin::WindowBuilder::new();
	let window = if fullscreen {
		window.with_fullscreen(monitor)
	} else {
		let (w, h) = monitor.get_dimensions();
		window.with_dimensions(w * 4/5, h * 4/5)
	};

	let context = glutin::ContextBuilder::new()
		.with_vsync(true)
	;
	(window, context)
}
```
It doesn't work correctly:
When I call it with cur_monitor `0` and fullscreen `true`, and then with the same monitor and fullscreen `false`, it STILL returns a fullscreen window (and I can see that it doesn't flicker/destroy the old fullscreen window). (The cur_monitor doesn't matter, the important part is calling it with fullscreen `false` after fullscreen `true`). If I then call it again with toggled fullscreen (`true`) I can see the flicker from destroying the old fullscreen window and then it creates the new fullscreen window.
So I can't get out of fullscreen mode by setting fullscreen to false, only when fullscreen has been set to false and then I increase cur_monitor, THEN it will give me a non-fullscreen window. But that's a workaround and shouldn't be necessary. 
It should build the window as non-fullscreen when `fullscreen` is `false`.

**Comment by francesca64** [comment]
I'm fairly certain this has been fixed. Feel free to re-open if I'm wrong.
