### ISSUE TITLE
X11 window is renamed after creation

### ISSUE THREAD

**Issue by carado** [tomaka/glutin#932]
In X11, using the window builder with `with_title` creates the window without a title and then very shortly after renames the window as it should.

The problem with that is that my window manager (i3) chooses on which desktop to open windows and whether to put them in floating mode based on their name, and sometimes it catches the window's name before it is changed, causing the window to briefly appear (in my case) in non-floating mode and then immediately after to go in floating mode (as it should be from the start); but the brief non-floating period can mess up other windows opened on the same desktop in i3.

I realize this is a very minor and specific nitpick, but I don't have that problem developing with GLFW, so surely it's possible to set a window's name directly as it is created on X11.

**Comment by tomaka** [comment]
Please open an issue in winit instead: https://github.com/tomaka/winit/issues
