### ISSUE TITLE
Getting raw pointer to platform GL context

### ISSUE THREAD

**Issue by ebkalderon** [tomaka/glutin#935]
I am writing some type-safe Rust bindings to [RenderDoc](https://renderdoc.org), a fairly popular graphics API debugger, and I am trying to get it to play nice with glutin-based applications.

When RenderDoc gets injected into the running application, the target application calls the [SetActiveWindow](https://renderdoc.org/docs/in_application_api.html#_CPPv215SetActiveWindow23RENDERDOC_DevicePointer22RENDERDOC_WindowHandle) function to tell RenderDoc which window to display the debug overlay and which graphics device to capture command lists from. To paraphrase the documentation:

```c
void SetActiveWindow(RENDERDOC_DevicePointer device, RENDERDOC_WindowHandle wndHandle)
```
> #### Note: 
> `RENDERDOC_DevicePointer` is a typedef to `void *`. The contents of it are API specific:
>
> * For D3D11 it must be the `ID3D11Device` device object.
> * **For OpenGL it must be the `HGLRC` or `GLXContext` context object.**
> * For Vulkan it must be the dispatch table pointer within the `VkInstance`. This is a pointer-sized value at the location pointed to by the `VkInstance`. NOTE - this is not the actual `VkInstance` pointer itself.
>
> `RENDERDOC_WindowHandle` is a typedef to `void *`. It is the platform specific `HWND`, `xcb_window_t`, or Xlib `Window`.

`glutin::GlWindow` can give me the raw window handle via the (albeit deprecated) `platform_window()` method, but I can't seem to acquire a raw pointer to the underlying GL context. Is there any way to do this with glutin at present? If not, how realistically could a feature like this be added? I am willing to make a pull request if needed.

**Comment by tomaka** [comment]
The `os` module contains all the platform-specific getters.
Making it possible to retrieve a pointer to the GL context should be done through a trait defined in this module.

**Comment by ebkalderon** [comment]
@tomaka Thanks for the guidance! However, I was thinking it might be more appropriate to add an unsafe `platform_context()` method to the `GlContext` trait instead. This would remain consistent with the existing `platform_window()` method in winit. Would you have anything against this approach?

**Comment by tomaka** [comment]
`platform_context` is too vague. If glutin creates an EGL context and you think it's a GLX context, then bad things may happen.

The `platform_window` method in winit is deprecated as well, so we shouldn't take inspiration from it.

**Comment by ebkalderon** [comment]
I see what you mean. But what if the resulting application doesn't care, e.g. RenderDoc? Should I instead use `#[cfg]` attributes to select the correct backend from the `os` module at compile time?

**Comment by tomaka** [comment]
All applications must care about what of context they have.

You quoted this in the OP:

> For OpenGL it must be the HGLRC or GLXContext context object.

Which I guess means that RenderDoc expects a GLX context.

**Comment by ebkalderon** [comment]
RenderDoc expects either a WGL context or a GLX context, depending on the platform. It is possible that other OpenGL context types may be accepted in future versions of the application. But that is beside the point that I'm trying to make.

Suppose I were to create a trait in the top-level `os` module, as was suggested in your initial reply, which looks roughly something like this:

```rust
pub trait ContextExt {
    type Handle;
    unsafe fn as_ptr_mut() -> *mut Handle;
}
```

Which types should implement this trait? I presume you meant for the various `Context` types defined in `platform`. If that's the case, then how would I handle contexts represented as `enum`s, e.g. `platform::windows::Context` and `platform::linux::Context`? What would you recommend I specify for the associated type? Or have I misunderstood something fundamental here?

**Comment by tomaka** [comment]
First of all, I was thinking of having a different trait in each submodule in `os`, but I guess having the same trait for all platforms is a nice solution as well.

As for handling contexts that are enums, you can just add methods to the enums. After all, the point of the ContextExt trait is just correctly handling visibility.

**Comment by ebkalderon** [comment]
Methods which return what type? Like I mentioned before, the idea of `ContextExt` is to return a type-safe mutable pointer to the underlying context handle, whatever that may be. What could I possibly set the `Handle` associated type if the backend being selected is unknown at compile time? Returning an `enum` containing pointers to the contexts might work, but is there be a prettier way?

**Comment by tomaka** [comment]
Just create another enum with the `Glx` and `Egl` variants, whose sole purpose is to be returned by the method in `ContextExt`.
