### ISSUE TITLE
A way to disable key repeats

### ISSUE THREAD

**Issue by ryanisaacg** [tomaka/glutin#943]
At least on Windows, key events seem to respond with a delay (especially when a key is being mashed) due to key repeat handling. Is there any way to disable this from glutin?

**Comment by vberger** [comment]
All inputs are actually handled by [winit](https://github.com/tomaka/winit), that glutin uses. Though I don't think winit has a way to disable that. Could you open your issue on the winit repository instead?

**Comment by ryanisaacg** [comment]
Okay, [opened an issue at winit](https://github.com/tomaka/winit/issues/310)
