### ISSUE TITLE
Renderer for headless context is wrong

### ISSUE THREAD

**Issue by ashkitten** [tomaka/glutin#946]
I'm using Nvidia on Linux, and when I create a context for a `Display` the OpenGL version string is `4.5.0 NVIDIA 387.12`, but when I create a `Headless` the OpenGL version string is `3.0 Mesa 17.2.2`, which is not what I want.

**Comment by js4785** [comment]
[Mesa is a requirement](https://github.com/tomaka/glutin/blob/master/src/platform/linux/mod.rs#L134) for a headless context. Is there a reason for this, or has it just not been generalized yet?

**Comment by ZeGentzy** [comment]
@js4785 That mistake on my part has been fixed in https://github.com/tomaka/glutin/pull/1058

**Comment by ZeGentzy** [comment]
Hey,

Running the OSMesa example from [here](https://github.com/tomaka/glutin/pull/1126/commits/461379e8d366ab3974411b9f6f34d4fd069ec1f8) gives me `OpenGL version 3.3 (Core Profile) Mesa 19.1.0-devel (git-15012077bc)`, which is the latest OGL version that llvmpipe supports.

This can be confirmed by running `LIBGL_ALWAYS_SOFTWARE=1 glxinfo | grep OpenGL`.

The sharing example reports, for me, both the headless context and windowed context having OGL 4.5:
`
OpenGL version 4.5 (Core Profile) Mesa 19.1.0-devel (git-15012077bc)
OpenGL version 4.5 (Core Profile) Mesa 19.1.0-devel (git-15012077bc)
`

Closing, as this is now fixed.
