### ISSUE TITLE
Allow creating context on existing window

### ISSUE THREAD

**Issue by ashkitten** [tomaka/glutin#947]
I'd like to be able to create a new OpenGL context on the existing root window for my live wallpaper program. Would it be possible to allow a new GlWindow to be created using an existing window ID? This would also allow for recreation of the context without recreating the window.

**Comment by tomaka** [comment]
That should be possible with platform-specific functions.

**Comment by osense** [comment]
@tomaka do you mean the platform-specific functions already in glutin? If so, could you offer any tips on where to get started?

**Comment by tomaka** [comment]
No, the platform-specific functions don't exist yet. I just wanted to indicate that this was the way to go.

**Comment by ZeGentzy** [comment]
Hey, see `SeparatedContext`s in https://github.com/tomaka/glutin/pull/1058 (soon to be in master). Let's you make a context on existing winit windows. If I understand correctly, this serves your purposes, otherwise reopen this issue.
