### ISSUE TITLE
Add (unsafe) API for getting the currently used windowing system/platform, the underlying platform display and context

### ISSUE THREAD

**Issue by sdroege** [tomaka/glutin#950]
It would be great if glutin could provide some functions for knowing the currently used windowing system and platform (e.g. X11/EGL, X11/GLX, Wayland/EGL, ...), and if there were functions for getting the underlying platform display and context.

This would be useful for integrating with other libraries that could share textures and other data with an existing GL context created by something else.

**Comment by vberger** [comment]
Many things are already available via the extension traits in [`glutin::os`](https://docs.rs/glutin/0.10.0/glutin/os/index.html), could you describe more specifically what you would need that is not already provided by this and the [`GlContext`](https://docs.rs/glutin/0.10.0/glutin/trait.GlContext.html) trait?

**Comment by sdroege** [comment]
I assume `Monitor` would give me the X11/EGL/Wayland display as native ID? Then what seems to be missing is something to know which of those would be returned.

For the GL context, having direct access to e.g. the `GLXContext` would be nicer but I could also always get that with `glXGetCurrentContext` (and corresponding APIs on other platforms) after making the context current.

**Comment by vberger** [comment]
No, `Monitor`s specifically refer to screens identifiers. The X11/wayland displays are retrieved from the `WindowExt` trait, via the methods `get_xlib_display` and `get_wayland_display`. Both return an option, which is `Some(_)` if this is the current platform, and `None` otherwise.

**Comment by sdroege** [comment]
Ah I see, thanks!

**Comment by sdroege** [comment]
Let's close this for now then, I *believe* this covers my use-cases except for the inconvenience with the context. But that's ok.
