### ISSUE TITLE
Outdated code on crates.io?

### ISSUE THREAD

**Issue by mstange** [tomaka/glutin#957]
The current version of https://crates.io/crates/servo-glutin is 0.13.1, which is newer than the 0.10.1 that's mentioned in the Cargo.toml of the master branch in this repository. However, the code that's currently on crates.io (and which I can see using cargo-clone) seems completely different. Why is that?

I'm interested in getting a version of glutin that contains #894. But in 0.13.1 there is no file called `src/platform/macos/helpers.rs`, there is only a file called `src/api/cocoa/helpers.rs` and that file does not contain the `NSOpenGLPFAAllowOfflineRenderers` attribute.

**Comment by vberger** [comment]
servo-glutin is a fork of glutin, and is hosted there: https://github.com/servo/glutin

This repository is the original glutin crate: https://crates.io/crates/glutin

**Comment by mstange** [comment]
Ah, that makes sense, thanks! So the repository link on https://crates.io/crates/servo-glutin is just wrong.
