### ISSUE TITLE
Split library with multiple -sys crates as dependencies

### ISSUE THREAD

**Issue by tomaka** [tomaka/glutin#96]
The x11, win32 and android ffis should be placed in separate repositories and added as dependencies.

**Comment by jdm** [comment]
Extracting src/x11/ffi.rs into https://github.com/servo/rust-xlib/ would be super.

**Comment by tomaka** [comment]
Glutin is on crates.io, so I need all depend crates to be on crates.io too.

**Comment by jdm** [comment]
I just came across [x11-rs](https://github.com/Daggerbot/x11-rs/), too, which is already on crates.io.
