### ISSUE TITLE
Problem with HiDPI - xfce, winit, gfx

### ISSUE THREAD

**Issue by norru** [tomaka/glutin#981]
Hello,

my last XFCE (or something else which happened around the same time) update caused a bit of turbulence in HiDPI handling in my winit/glutin/gfx app, kinda breaking it. I would appreciate some assistance in tracking it down.

In short, it's a gfx based simulation running in a 1280x1024 window by default. Here's how I'm creating the window (extra code omitted)
```rust
	let builder = glutin::WindowBuilder::new().with_dimensions(1280, 1024)
	let context_builder = glutin::ContextBuilder::new();

	let (window,
		mut device,
		mut factory,
		mut frame_buffer,
		mut depth_buffer) =
		gfx_window_glutin::init::<formats::ScreenColorFormat, formats::ScreenDepthFormat>(
			builder,
			context_builder,
			&events_loop,
		);

	let (w, h, _, _) = frame_buffer.get_dimensions();
	let hidpi_factor = window.hidpi_factor();
```

Before the update: ```w = 1280```, ```h=1024```, ```hidpi_factor=1.0```
After the update: ```w = 2133```,```h=1706```, ```hidpi_factor=1.666```

I'm ok handling a frame buffer that large - in fact I'm even rendering on a 4x MSAA offscreen buffer and then resolving/blitting over - the problem is that the *actual* client area of the window is still *1280x1024* physical pixels, so a large part of the frame buffer is clipped away on screen.

I have worked the problem around temporarily by enforcing 96DPI for my monitor via xorg.conf (which restores the "before the update" behaviour), but I think it's unreasonable to ask all my users to do the same.

This could well be an issue with my window manager, my desktop compositor, or whatever, but it's upon me to find a workaround while the issue is being resolved - if ever (those things tend to take months or year to make it to distro).

I'd rather like to have an option to opt-out of automatic HIDPI handling by having an option to specify a hidpi factor via the window builder, such as:

```let builder = glutin::WindowBuilder::new().with_dimensions(1280, 1024).with_hidpi(1.0)``` which would bypass the x11 query.

Other ideas?

Thanks
Nico

**Comment by norru** [comment]
I think I've tracked it down to here (glutin 0.20.0):

```rust
fn get_window_dimensions(window: &glutin::GlWindow) -> texture::Dimensions {
    // https://github.com/tomaka/winit/pull/370
    #[cfg(target_os = "emscripten")]
    let (width, height) = emscripten::get_canvas_size();
    #[cfg(not(target_os = "emscripten"))]
    let (width, height) = {
        let (w, h) = window.get_inner_size().unwrap(); // <--- oooh, always pixels!
        let factor = window.hidpi_factor();
        ((w as f32 * factor) as _, (h as f32 * factor) as _)
    };
    let aa = window
        .get_pixel_format().multisampling
        .unwrap_or(0) as texture::NumSamples;

    (width, height, 1, aa.into())
}
```
```window.get_inner_size()``` appears to always return the client size are of the window in pixels, regardless of the actual DPI.

I have also found an easier workaround, which can be used to repro the error:

```xrandr --dpi 96; cargo run```  hides the issue
```xrandr --dpi 192; cargo run``` reproduces the issue (tried on a different device which was not having any problem before)

**Comment by daboross** [comment]
Do you think this could be the same issue glium ran into? https://github.com/glium/glium/issues/1657

Glium contained a similar manual adjustment on the result of `get_inner_size`. It was correct to do so until https://github.com/tomaka/winit/commit/48902297b7bd02fc20f3ae7012074c6b93674980, which changed get_inner_size to return raw pixels instead of DPI scaled points.

This is the fix for glium: https://github.com/glium/glium/commit/df032996ef8354f8512f732f91107760e568a99f. Something similar might be doable in gfx?

**Comment by norru** [comment]
Yeah, I think this is the same issue.

HiDPI needs to be handled consistently for all stages of window handling. At the moment, one approach is used at window creation stage, but a different one to handle the "hidpi scaling".

I think that,
1) the expected size of a window created with ```.with_dimensions(WIDTH, HEIGHT)``` should A) take the hidpi factor into account by creating a windows that is WIDTHxHEIGHT * hidpi_factor pixels in size and B) allow the user to opt out and force a specific hidpi. E.g. ```.with_desired_hidpi(Some(1.0))``` to override the detected settings.

2) keep measuring everything all the way down to pixels, including all the "internal" calls such as ```get_window_, but let the application **query** the hidpi settings via  ```window.hidpi_factor()``` so it can still adjust its own screen layout to take DPI into account.

**Comment by francesca64** [comment]
This should be tracked on winit instead: https://github.com/tomaka/winit/milestone/1

**Comment by francesca64** [comment]
Closing this in favor of tomaka/winit#105
