### ISSUE TITLE
Crash with `set_inner_size` on OSX

### ISSUE THREAD

**Issue by expenses** [tomaka/glutin#983]
Hi, I was running into a wierd issue earlier and I found that if you set the inner size of a window on OSX to something long and thin, it crashes the OS back to the login screen. Example code is as follows:

```rust
extern crate glutin;

fn main() {
    let mut events_loop = glutin::EventsLoop::new();
    let window = glutin::Window::new(&events_loop).unwrap();
    window.set_inner_size(10_000, 50);

    events_loop.run_forever(|_| glutin::ControlFlow::Continue);
}
```

Edit: specs are
```
Model: MacBook Pro (13-inch, 2017)
Display: 13.3-inch (2560 x 1600)
Graphics Card: Intel Iris Plus Graphics 640 1536 MB
```

**Comment by mitchmindtree** [comment]
Thanks for posting this @expenses!

Is there any chance you could run this again with `RUST_BACKTRACE=1` and post the whole output here? I think this is more likely an issue with the winit crate however if you could do this it would help to confirm.

**Comment by francesca64** [comment]
I haven't been able to reproduce this on High Sierra.

**Comment by ZeGentzy** [comment]
Feel free to reopen if still an issue.
