### ISSUE TITLE
Moving GlWindow to a different Thread

### ISSUE THREAD

**Issue by LuFans** [tomaka/glutin#985]
I created a GlWindow on the main thread and specified the shared lists of the Context Builder to be the Context of my main window. Then I moved that window into another Thread and tried to make it current.
The call to make_current() failed with the Error: "other os error". I need a current Context on the Thread to fill up some Buffers and I can't create the GlWindow on the thread since the lifetime of the refrence to the main window is to short. When I do the same thing in C++ with GLFW it works.
Is this behavior desired or has anybody some experience with using a shared Context on a diffrent Thread with glutin? 
Thank you in advance.

**Comment by tomaka** [comment]
You need to maintain a 1 to 1 mapping between threads and Gl contexts. If you want to use a context from a separate thread, you need to unbind it from the first thread first.

**Comment by LuFans** [comment]
And how do I remove that binding
This is the code...
`
            let context = glutin::ContextBuilder::new()
                .with_gl(glutin::GlRequest::Latest)
                .with_shared_lists(window.context());
            let mut events_loop = glutin::EventsLoop::new();
            let window = glutin::WindowBuilder::new()
                .with_visibility(false)
                .with_dimensions(1, 1);


            let gl_window = glutin::GlWindow::new(window, context, &events_loop).unwrap();


            let handle = thread::spawn(move || {
                
            
                unsafe {
                    if let Err(error) = gl_window.make_current() {
                        info!("Make Context Current Error: {}", error);
                    }
                    gl::load_with(|s| gl_window.get_proc_address(s) as *const _);
                }
           }
`

**Comment by tomaka** [comment]
Err, yes glutin doesn't have an option to unbind a context unfortunately.

**Comment by ZeGentzy** [comment]
https://github.com/tomaka/glutin/issues/784
