### ISSUE TITLE
Timing example

### ISSUE THREAD

**Issue by benkonz** [tomaka/glutin#990]
Does glutin have an equivelent to the GLFW `glfwGetTime()` function? I am looking for a way to limit the of my application to 60 refreshes per second, but in order to do that I need some way to get the current time.

**Comment by mitchmindtree** [comment]
@benkonz Is the [std::time](https://doc.rust-lang.org/std/time/index.html) module sufficient for your needs?

**Comment by benkonz** [comment]
Yeah, the std::time api should be sufficient. Thanks.
