### ISSUE TITLE
Windows: getting a GL context into IDCompositionVisual::SetContent

### ISSUE THREAD

**Issue by SimonSapin** [tomaka/glutin#993]
I’m prototyping using Windows’ DirectComposition API, to take advantage of the desktop’s compositor. I’d like to make a demo with two (or more) OpenGL contexts being composited together. After I create a context with glutin, I need to find a way to turn it into something I can pass to [`IDCompositionVisual::SetContent`](https://msdn.microsoft.com/en-us/library/windows/desktop/hh449157(v=vs.85).aspx). It accepts different types of things:

* A `IDCompositionSurface` that can be accessed as a Direct2D device context or a DXGI surface
* A `IDXGISwapChain1`
* A wrapper created from a `HANDLE`
* A wrapper created from a `HWND`

That last one seems most promising, since `glutin::Window` has a `get_hwnd` (trait) method.

Creating a second window with glutin and using its `HWND` that way works (the GL contents get composited onto the first window), but now the app has two visible windows (with the content visible twice). If I create the second window with `.with_visibility(false)` it stops showing up, but also stops rendering at all in the first window.

If I set `DWMWA_CLOAK` to true with `DwmSetWindowAttribute` [as suggested](https://msdn.microsoft.com/en-us/library/windows/desktop/hh437407(v=vs.85).aspx) I can have the second window stop being visible independently while still having it render for composition, but I can only do so after glutin has finished creating it, so on startup it is still visible for a short while.

If I create with `.with_visibility(false)`, then set `DWMWA_CLOAK`, then call `glutin::Window::show`, the program freezes. Visual Studio shows glutin’s `winuser::ShowWindow(self.window.0, winuser::SW_SHOW)` call at the top (bottom?) of the stack, but nothing further.

----

Is there some other way to create a window that’s hidden/cloaked from the start without making it stop rendering? Or maybe to get a an OpenGL context into a `IDCompositionVisual` without crating a window at all?

**Comment by glennw** [comment]
@SimonSapin my *very limited* understanding of this is that the simplest way to get accelerated interop between GL surfaces and DXGI is by running on top of ANGLE, which provides some custom extension points to do the interop (since when running under ANGLE, the GL implementation is *actually* a DirectX device). This would also match up with how we're planning to eventually do the GL interop on Windows for other DXGI interfaces (such as video codecs etc).

**Comment by SimonSapin** [comment]
Alright, I’ll look into constructing a `IDXGISwapChain1` with ANGLE. Closing here since this isn’t much glutin-related anymore (I’ll likely use winit without glutin), but anyone feel free to comment if you have more suggestions.

**Comment by SimonSapin** [comment]
For future archeologists: the solution was passing a DXGI swap chain’s back buffer to ANGLE’s `eglCreatePbufferFromClientBuffer` with `D3D_TEXTURE_ANGLE`: https://github.com/servo/webrender/pull/2458/files#diff-ae656b652020bfb92ec0352234d5623b
